// Full A2 grammar translations (g1–g8) — situation, tip, blocks, quiz explanations.
const P = (uz, ru) => ({ uz, ru });
export const A2_TR_1 = {
  g1: {
    situation: P("“Kecha nima qilding?” “Film ko'rdim va erta uxladim.” — Aniq o'tgan vaqtda tugagan ish-harakatlar uchun past simple ishlatiladi.", "«Что ты делал вчера?» «Посмотрел фильм и рано лёг спать.» — Past simple используется для завершённых действий в определённое время в прошлом."),
    tip: P("didn't va did dan keyin hech qachon o'tgan zamon shaklini ishlatmang: 'I didn't went' — xato → 'I didn't go'. O'tgan zamonni 'did' o'zi ko'rsatib turibdi.", "После didn't и did никогда не используйте форму прошедшего времени: 'I didn't went' — ошибка → 'I didn't go'. Прошедшее время уже показано словом did."),
    blocks: [
      { h: P("To'g'ri fe'llar: + -ed", "Правильные глаголы: + -ed"), p: [P("Ko'p fe'llarga -ed qo'shiladi. -e bilan tugaganlarga faqat -d; undosh + y → -ied; qisqa urg'uli unlidan keyin oxirgi undosh ikkilanadi.", "Большинство глаголов получают -ed. Оканчивающиеся на -e добавляют только -d; согласная + y → -ied; после краткой ударной гласной конечная согласная удваивается.")] },
      { h: P("Noto'g'ri fe'llar", "Неправильные глаголы"), p: [P("Ko'p ishlatiladigan fe'llarning aksariyati noto'g'ri — ularni yodlash kerak.", "Многие частые глаголы — неправильные, их нужно выучить.")] },
      { h: P("Inkor va savollar", "Отрицания и вопросы"), p: [P("Inkor uchun didn't + fe'lning asosiy shakli, savol uchun Did + ega + asosiy shakl. Asosiy fe'l boshlang'ich shakliga qaytadi.", "Для отрицания: didn't + начальная форма; для вопроса: Did + подлежащее + начальная форма. Основной глагол возвращается к начальной форме.")] },
      { h: P("Vaqt iboralari", "Выражения времени"), p: [P("Past simple ko'pincha shu so'zlar bilan keladi: yesterday, last night/week, two days ago, in 2010, when I was young.", "Past simple часто идёт со словами: yesterday, last night/week, two days ago, in 2010, when I was young.")] },
    ],
    quiz: [
      P("To'g'ri fe'l + -ed: played.", "Правильный глагол + -ed: played."),
      P("'go' — noto'g'ri fe'l: went.", "'go' — неправильный глагол: went."),
      P("Noto'g'ri: eat → ate.", "Неправильный: eat → ate."),
      P("go → went.", "go → went."),
      P("Undosh + y → -ied: studied.", "Согласная + y → -ied: studied."),
      P("To'g'ri fe'l: watched.", "Правильный глагол: watched."),
      P("O'tgan zamon inkori: didn't come.", "Отрицание в прошедшем: didn't come."),
      P("O'tgan zamon savoli: Did you see…?", "Вопрос в прошедшем: Did you see…?"),
      P("Noto'g'ri: buy → bought.", "Неправильный: buy → bought."),
      P("Noto'g'ri: lose → lost.", "Неправильный: lose → lost."),
      P("'didn't' dan keyin asosiy shakl: I didn't go home.", "После didn't — начальная форма: I didn't go home."),
      P("Noto'g'ri: write → wrote; send → sent.", "Неправильные: write → wrote; send → sent."),
      P("Did + asosiy shakl: Did you go out?", "Did + начальная форма: Did you go out?"),
      P("'we were' (ko'plik) va noto'g'ri leave → left.", "'we were' (мн. число) и неправильный leave → left."),
      P("can → could.", "can → could."),
    ],
  },
  g2: {
    situation: P("“Kecha soat 8da televizor ko'rayotgan edim, birdan telefon jiringladi.” — Past continuous uzunroq fon harakatini, past simple esa uni bo'lgan qisqa harakatni bildiradi.", "«Вчера в 8 я смотрел телевизор, когда зазвонил телефон.» — Past continuous задаёт длительный фон, past simple — короткое действие, которое его прерывает."),
    tip: P("Qisqa, tugagan harakat uchun past simple, uzun fon harakati uchun past continuous: 'I was walking home when it started to rain.'", "Для короткого завершённого действия — past simple, для длительного фона — past continuous: 'I was walking home when it started to rain.'"),
    blocks: [
      { h: P("Shakl: was/were + -ing", "Форма: was/were + -ing"), p: [P("was (I/he/she/it) yoki were (you/we/they) + fe'l-ing.", "was (I/he/she/it) или were (you/we/they) + глагол-ing.")] },
      { h: P("Bo'lingan harakatlar", "Прерванные действия"), p: [P("Uzun harakat — past continuous, uni bo'lgan qisqa harakat — past simple; ko'pincha when yoki while bilan bog'lanadi.", "Длинное действие — past continuous, прерывающее короткое — past simple; часто соединяются when или while.")] },
      { h: P("Ikkita parallel harakat", "Два одновременных действия"), p: [P("Bir vaqtda davom etgan ikkita uzun harakat uchun ikkalasida ham past continuous.", "Для двух длительных одновременных действий — оба в past continuous.")] },
      { h: P("Inkor va savollar", "Отрицания и вопросы"), p: [P("Inkor: wasn't/weren't + -ing. Savol: Was/Were + ega + -ing?", "Отрицание: wasn't/weren't + -ing. Вопрос: Was/Were + подлежащее + -ing?")] },
    ],
    quiz: [
      P("Davom etayotgan harakat (I) → was having.", "Действие в процессе (I) → was having."),
      P("Fon harakati (they) → were playing.", "Фоновое действие (they) → were playing."),
      P("Davomida (she) → was reading.", "В процессе (she) → was reading."),
      P("'we' bilan → were watching.", "С 'we' → were watching."),
      P("he + was + -ing.", "he + was + -ing."),
      P("Uzunroq harakat → was showering.", "Более длинное действие → was showering."),
      P("Fon harakati (she) → was cooking.", "Фоновое действие (she) → was cooking."),
      P("Inkor (they) → weren't working.", "Отрицание (they) → weren't working."),
      P("Savol (you) → Were you sleeping?", "Вопрос (you) → Were you sleeping?"),
      P("To'satdan bo'lgan harakat 'when' bilan keladi.", "Внезапное прерывающее действие вводится с 'when'."),
      P("'they' bilan 'were': They were playing.", "С 'they' — 'were': They were playing."),
      P("Ikkita parallel o'tgan harakat → ikkalasi continuous.", "Два параллельных действия в прошлом → оба continuous."),
      P("Qisqa 'arrived' + uzun fon 'was cooking'.", "Короткое 'arrived' + длинный фон 'was cooking'."),
      P("Savol (you) → Were you doing?", "Вопрос (you) → Were you doing?"),
      P("Uzun 'was reading' + bo'luvchi 'called'.", "Длинное 'was reading' + прерывающее 'called'."),
    ],
  },
  g3: {
    situation: P("“I have visited London twice.” Qachonligini aytmaymiz — muhimi hozirgi tajriba, aniq vaqt emas.", "«I have visited London twice.» Мы не говорим когда — важен опыт сейчас, а не точное время."),
    tip: P("Present perfect'ni tugagan o'tgan vaqt bilan ishlatmang: 'I saw her yesterday' (past simple) to'g'ri, 'I have seen her yesterday' — xato. Vaqt tugamagan yoki aytilmagan bo'lsa — present perfect.", "Не используйте present perfect с законченным временем: 'I saw her yesterday' (past simple), а не 'I have seen her yesterday'. Present perfect — когда время не закончено или не указано."),
    blocks: [
      { h: P("Shakl: have/has + sifatdosh", "Форма: have/has + причастие"), p: [P("have (I/you/we/they) yoki has (he/she/it) + fe'lning 3-shakli (done, gone, seen, been).", "have (I/you/we/they) или has (he/she/it) + 3-я форма глагола (done, gone, seen, been).")] },
      { h: P("ever / never (tajriba)", "ever / never (опыт)"), p: [P("Hayotdagi tajriba haqida: savollarda ever, inkorda never.", "Об опыте в жизни: в вопросах ever, в отрицаниях never.")] },
      { h: P("just / already / yet", "just / already / yet"), p: [P("just = hozirgina; already = kutilganidan erta; yet = savol va inkorlarda, gap oxirida.", "just = только что; already = раньше ожидаемого; yet = в вопросах и отрицаниях, в конце предложения.")] },
      { h: P("for / since", "for / since"), p: [P("for + davr (muddat), since + boshlanish nuqtasi — hozirgacha davom etayotgan holatlar uchun.", "for + период, since + точка отсчёта — для ситуаций, продолжающихся до сих пор.")] },
    ],
    quiz: [
      P("Present perfect: have finished.", "Present perfect: have finished."),
      P("'she' bilan: has been.", "С 'she': has been."),
      P("see → saw → seen.", "see → saw → seen."),
      P("have + sifatdosh: have seen.", "have + причастие: have seen."),
      P("'they' bilan: have just arrived.", "С 'they': have just arrived."),
      P("Tajriba haqidagi savolda 'ever'.", "В вопросе об опыте — 'ever'."),
      P("Inkor tajriba: never.", "Отрицательный опыт: never."),
      P("Savolda 'yet' gap oxirida keladi.", "В вопросе 'yet' стоит в конце."),
      P("Vaqt nuqtasi → since 2015.", "Точка времени → since 2015."),
      P("Davr → for ten years.", "Период → for ten years."),
      P("'yesterday' (tugagan vaqt) bilan past simple: I saw her yesterday.", "С 'yesterday' (законченное время) — past simple: I saw her yesterday."),
      P("has + sifatdosh (send → sent).", "has + причастие (send → sent)."),
      P("'yet' savol oxirida.", "'yet' — в конце вопроса."),
      P("'for three days' + present perfect 'have had'.", "'for three days' + present perfect 'have had'."),
      P("Borib qaytilgan tajriba uchun 'been': I have been to Rome.", "Об опыте «съездил и вернулся» — 'been': I have been to Rome."),
    ],
  },
  g4: {
    situation: null,
    tip: P("Gapirayotib qabul qilingan qaror — will: 'I'll have the chicken, please.' Oldindan rejalashtirilgan ish — going to: 'I'm going to start a new job.'", "Решение, принятое в момент речи — will: 'I'll have the chicken, please.' Заранее запланированное — going to: 'I'm going to start a new job.'"),
    blocks: [
      { h: P("will — qarorlar va bashoratlar", "will — решения и предсказания"), p: [P("will + asosiy fe'l: oniy qarorlar, takliflar, va'dalar va umumiy bashoratlar uchun. Qisqa shakl: 'll; inkor: won't.", "will + начальная форма: мгновенные решения, предложения, обещания и общие предсказания. Краткая форма: 'll; отрицание: won't.")] },
      { h: P("be going to — rejalar va niyatlar", "be going to — планы и намерения"), p: [P("be going to + fe'l: oldindan qabul qilingan rejalar va ko'rinib turgan dalilga asoslangan bashoratlar uchun.", "be going to + глагол: для уже принятых планов и предсказаний на основе видимых признаков.")] },
      { h: P("will yoki going to?", "will или going to?"), p: [P("Hozir qabul qilingan qaror = will; oldin qabul qilingan reja = going to.", "Решение сейчас = will; план, принятый раньше = going to.")] },
      { h: P("Kelishuvlar uchun present continuous", "Present continuous для договорённостей"), p: [P("Aniq vaqti bor kelishuvlar uchun present continuous ham keng ishlatiladi.", "Для договорённостей с точным временем также обычен present continuous.")] },
    ],
    quiz: [
      P("Bashorat → will rain.", "Предсказание → will rain."),
      P("Qabul qilingan reja → are going to visit.", "Принятый план → are going to visit."),
      P("will not = won't.", "will not = won't."),
      P("Oniy qaror → I'll answer it.", "Мгновенное решение → I'll answer it."),
      P("Dalilga asoslangan bashorat → is going to rain.", "Предсказание по признакам → is going to rain."),
      P("Kelajakdagi fakt → will be.", "Будущий факт → will be."),
      P("Reja → are going to move.", "План → are going to move."),
      P("Va'da (inkor) → won't tell.", "Обещание (отрицание) → won't tell."),
      P("Rejalar haqida savol → are you going to do?", "Вопрос о планах → are you going to do?"),
      P("Hozir qaror → I'll help you.", "Решение сейчас → I'll help you."),
      P("'will' dan keyin asosiy shakl: I will call you.", "После 'will' — начальная форма: I will call you."),
      P("Hozirgi taklif → I'll close the window.", "Предложение сейчас → I'll close the window."),
      P("Vaqti aniq kelishuv → present continuous.", "Договорённость со временем → present continuous."),
      P("Reja → going to start; bashorat → will succeed.", "План → going to start; предсказание → will succeed."),
      P("Dalilga asoslangan → is going to have.", "По признакам → is going to have."),
    ],
  },
  g5: {
    situation: null,
    tip: P("Ikki shaklni aralashtirmang: 'more taller' va 'most biggest' — xato. Yoki -er/-est, yoki more/most — hech qachon ikkalasi birga emas.", "Не смешивайте формы: 'more taller' и 'most biggest' — ошибка. Либо -er/-est, либо more/most, но никогда вместе."),
    blocks: [
      { h: P("Qisqa sifatlar", "Короткие прилагательные"), p: [P("Bir bo'g'inli sifatlar: -er (qiyosiy) va -est (orttirma). Qisqa unlidan keyin undosh ikkilanadi; -y → -ier/-iest.", "Односложные: -er (сравнительная) и -est (превосходная). После краткой гласной согласная удваивается; -y → -ier/-iest.")] },
      { h: P("Uzun sifatlar", "Длинные прилагательные"), p: [P("Ikki va undan ko'p bo'g'in: more (qiyosiy) va the most (orttirma).", "Два и более слога: more (сравнительная) и the most (превосходная).")] },
      { h: P("than va the", "than и the"), p: [P("Qiyosiy shakldan keyin than, orttirma shakldan oldin the.", "После сравнительной — than, перед превосходной — the.")] },
      { h: P("Noto'g'ri shakllar", "Неправильные формы"), p: [P("Ba'zi sifatlar noto'g'ri o'zgaradi: good → better → the best.", "Некоторые прилагательные изменяются нестандартно: good → better → the best.")] },
    ],
    quiz: [
      P("Qisqa sifat + -er: heavier.", "Короткое прилагательное + -er: heavier."),
      P("Qisqa sifatning orttirmasi: the tallest.", "Превосходная короткого: the tallest."),
      P("faster than.", "faster than."),
      P("Undosh ikkilanadi: bigger.", "Согласная удваивается: bigger."),
      P("Uzun sifat → more expensive.", "Длинное прилагательное → more expensive."),
      P("Noto'g'ri orttirma: the best.", "Неправильная превосходная: the best."),
      P("Noto'g'ri qiyosiy: worse.", "Неправильная сравнительная: worse."),
      P("-y → -iest: happiest.", "-y → -iest: happiest."),
      P("Uzun sifat orttirmasi: the most intelligent.", "Превосходная длинного: the most intelligent."),
      P("heavier than.", "heavier than."),
      P("-er bilan 'more' ishlatilmaydi: cheaper than.", "С -er не используют 'more': cheaper than."),
      P("Orttirma: the biggest city in the country.", "Превосходная: the biggest city in the country."),
      P("'the tallest' (qisqa sifatga 'most' qo'shilmaydi).", "'the tallest' (с короткими 'most' не нужен)."),
      P("more difficult than … the most difficult.", "more difficult than … the most difficult."),
      P("good → better (noto'g'ri).", "good → better (неправильная форма)."),
    ],
  },
  g6: {
    situation: null,
    tip: P("'Good' — sifat, uning ravishi well: 'She is a good singer', lekin 'She sings well.' 'She sings good' — xato.", "'Good' — прилагательное, его наречие — well: 'She is a good singer', но 'She sings well.' 'She sings good' — ошибка."),
    blocks: [
      { h: P("Ravish yasash: + -ly", "Образование наречий: + -ly"), p: [P("Ko'p ravishlar sifatga -ly qo'shib yasaladi. -y → -ily; -le → -ly.", "Большинство наречий: прилагательное + -ly. -y → -ily; -le → -ly.")] },
      { h: P("Noto'g'ri ravishlar", "Неправильные наречия"), p: [P("Ba'zi ravishlar noto'g'ri yoki sifat bilan bir xil: fast, hard, well.", "Некоторые наречия нестандартны или совпадают с прилагательным: fast, hard, well.")] },
      { h: P("O'rni", "Позиция"), p: [P("Ravish odatda fe'ldan (yoki to'ldiruvchidan) keyin keladi.", "Наречие обычно стоит после глагола (или после дополнения).")] },
      { h: P("Sifat yoki ravish?", "Прилагательное или наречие?"), p: [P("Sifat otni, ravish fe'lni izohlaydi.", "Прилагательное описывает существительное, наречие — глагол.")] },
    ],
    quiz: [
      P("Holat ravishi: beautifully.", "Наречие образа действия: beautifully."),
      P("quick → quickly.", "quick → quickly."),
      P("'fast' ravish va sifat sifatida bir xil.", "'fast' одинаково как наречие и прилагательное."),
      P("Ravish: slowly.", "Наречие: slowly."),
      P("good → well (noto'g'ri).", "good → well (неправильное)."),
      P("'hard' (= tirishib) — ravish; 'hardly' = deyarli emas.", "'hard' (= усердно) — наречие; 'hardly' = почти не."),
      P("'good'ning ravishi 'well'.", "Наречие от 'good' — 'well'."),
      P("-y → -ily: happily.", "-y → -ily: happily."),
      P("Ravish: carefully.", "Наречие: carefully."),
      P("'speaks quietly' — ravish bilan.", "'speaks quietly' — с наречием."),
      P("Ravish 'well': He sings very well.", "Наречие 'well': He sings very well."),
      P("Sifat 'careful' (worker) + ravish 'carefully' (works).", "Прилагательное 'careful' (worker) + наречие 'carefully' (works)."),
      P("Ravish to'ldiruvchidan keyin: answered the question correctly.", "Наречие после дополнения: answered the question correctly."),
      P("Sifat 'easy' (test) + ravish 'easily' (finished).", "Прилагательное 'easy' (test) + наречие 'easily' (finished)."),
      P("angry → angrily.", "angry → angrily."),
    ],
  },
  g7: {
    situation: null,
    tip: P("Darak gaplarda 'much'/'many' o'rniga a lot of tabiiyroq: 'I have a lot of work', 'I have much work' emas.", "В утвердительных предложениях a lot of звучит естественнее, чем much/many: 'I have a lot of work', а не 'I have much work'."),
    blocks: [
      { h: P("much va many", "much и many"), p: [P("many — sanaladigan otlar bilan, much — sanalmaydigan otlar bilan; asosan savol va inkorlarda.", "many — с исчисляемыми, much — с неисчисляемыми; в основном в вопросах и отрицаниях.")] },
      { h: P("a lot of / lots of", "a lot of / lots of"), p: [P("a lot of (yoki lots of) — ikkala tur ot bilan, odatda darak gaplarda.", "a lot of (или lots of) — с обоими типами, обычно в утверждениях.")] },
      { h: P("a few va a little", "a few и a little"), p: [P("a few — sanaladigan, a little — sanalmaydigan otlar bilan: 'ozgina' ma'nosida.", "a few — с исчисляемыми, a little — с неисчисляемыми: «немного».")] },
      { h: P("too much / too many / enough", "too much / too many / enough"), p: [P("too much/many = keragidan ortiq; enough = yetarli.", "too much/many = больше, чем нужно; enough = достаточно.")] },
    ],
    quiz: [
      P("Sanaladigan 'apples' → many.", "Исчисляемое 'apples' → many."),
      P("Sanalmaydigan 'water' → much.", "Неисчисляемое 'water' → much."),
      P("Darak gap → a lot of.", "Утверждение → a lot of."),
      P("Sanaladigan, oz miqdor → a few.", "Исчисляемое, немного → a few."),
      P("Sanalmaydigan, oz miqdor → a little.", "Неисчисляемое, немного → a little."),
      P("Sanalmaydigan + inkor → much.", "Неисчисляемое + отрицание → much."),
      P("Sanaladigan + inkor → many.", "Исчисляемое + отрицание → many."),
      P("Sanaladigan, ortiqcha → too many.", "Исчисляемое, избыток → too many."),
      P("Sanalmaydigan, oz → a little.", "Неисчисляемое, немного → a little."),
      P("Sanalmaydigan darak → a lot of.", "Неисчисляемое утверждение → a lot of."),
      P("Sanaladigan darak → 'many' yoki 'a lot of' friends.", "Исчисляемое утверждение → 'many' или 'a lot of' friends."),
      P("Sanalmaydigan 'much juice' + sanaladigan 'a few apples'.", "Неисчисляемое 'much juice' + исчисляемое 'a few apples'."),
      P("'enough' otdan oldin: enough chairs.", "'enough' перед существительным: enough chairs."),
      P("Sanalmaydigan 'much money' + 'a little'.", "Неисчисляемое 'much money' + 'a little'."),
      P("Darak + sanalmaydigan → a lot of coffee.", "Утверждение + неисчисляемое → a lot of coffee."),
    ],
  },
  g8: {
    situation: null,
    tip: P("Fe'llarni qisqa iboralar bilan yodlang: 'want to go', 'enjoy going'. Ikkilansangiz: want, need, hope, decide → to; enjoy, finish, stop → -ing.", "Учите глаголы короткими фразами: 'want to go', 'enjoy going'. Если сомневаетесь: want, need, hope, decide → to; enjoy, finish, stop → -ing."),
    blocks: [
      { h: P("Fe'l + to-infinitiv", "Глагол + to-инфинитив"), p: [P("Bu fe'llardan keyin to + asosiy shakl: want, would like, need, decide, hope, plan, promise, learn, try.", "После этих глаголов to + начальная форма: want, would like, need, decide, hope, plan, promise, learn, try.")] },
      { h: P("Fe'l + -ing", "Глагол + -ing"), p: [P("Bu fe'llardan keyin -ing shakli: like, love, enjoy, hate, finish, stop, mind, suggest, practise.", "После этих глаголов форма -ing: like, love, enjoy, hate, finish, stop, mind, suggest, practise.")] },
      { h: P("Maqsad infinitivи", "Инфинитив цели"), p: [P("Nega qilishingizni tushuntirish uchun to + fe'l (maqsad).", "Чтобы объяснить зачем — to + глагол (цель).")] },
      { h: P("like + -ing / would like + to", "like + -ing / would like + to"), p: [P("like + -ing = umuman yoqtirish; would like + to = hozir istayman.", "like + -ing = нравится вообще; would like + to = хочу сейчас.")] },
    ],
    quiz: [
      P("want + to: to go.", "want + to: to go."),
      P("enjoy + -ing: dancing.", "enjoy + -ing: dancing."),
      P("hope + to: to win.", "hope + to: to win."),
      P("finish + -ing: eating.", "finish + -ing: eating."),
      P("need + to: to see.", "need + to: to see."),
      P("decide + to: to stay.", "decide + to: to stay."),
      P("mind + -ing: closing.", "mind + -ing: closing."),
      P("Maqsad → to borrow.", "Цель → to borrow."),
      P("stop + -ing: working.", "stop + -ing: working."),
      P("learn + to: to swim.", "learn + to: to swim."),
      P("enjoy + -ing: I enjoy reading books.", "enjoy + -ing: I enjoy reading books."),
      P("want + to (to become); o'rgatish uchun → to teach.", "want + to (to become); учить → to teach."),
      P("would like + to: I'd like to swim.", "would like + to: I'd like to swim."),
      P("finish + -ing (working) + decide + to (to go).", "finish + -ing (working) + decide + to (to go)."),
      P("Maqsad: to + asosiy shakl → to pass.", "Цель: to + начальная форма → to pass."),
    ],
  },
};
