// Full A2 grammar translations (g9–g15).
const P = (uz, ru) => ({ uz, ru });
export const A2_TR_2 = {
  g9: {
    situation: null,
    tip: P("Tugagan vaqt so'zi past simple'ni talab qiladi. 'I have finished it yesterday' — xato → 'I finished it yesterday.'", "Слово законченного времени требует past simple. 'I have finished it yesterday' — ошибка → 'I finished it yesterday.'"),
    blocks: [
      { h: P("Tugagan va tugamagan vaqt", "Законченное и незаконченное время"), p: [P("Tugagan vaqt so'zi bilan (yesterday, last week, in 2010) — past simple. Vaqt aytilmagan yoki tugamagan bo'lsa (today, this week, ever) — present perfect.", "Со словом законченного времени (yesterday, last week, in 2010) — past simple. Если время не указано или не закончено (today, this week, ever) — present perfect.")] },
      { h: P("Tajriba yoki aniq voqea", "Опыт или конкретное событие"), p: [P("Present perfect = istalgan vaqtdagi tajriba. Past simple = aniq tugallangan voqea.", "Present perfect = опыт в любое время. Past simple = конкретное завершённое событие.")] },
      { h: P("Hozirgi natija yoki shunchaki o'tmish", "Результат сейчас или просто прошлое"), p: [P("Present perfect hozirgi natijani ko'rsatadi; past simple faqat tugagan ishni xabar qiladi.", "Present perfect показывает результат сейчас; past simple просто сообщает о завершённом действии.")] },
      { h: P("Belgi so'zlar", "Слова-сигналы"), p: [P("Past simple: yesterday, ago, last…, in 2015. Present perfect: ever, never, just, already, yet, recently, since, for.", "Past simple: yesterday, ago, last…, in 2015. Present perfect: ever, never, just, already, yet, recently, since, for.")] },
    ],
    quiz: [
      P("'yesterday' → past simple: finished.", "'yesterday' → past simple: finished."),
      P("Tajriba → present perfect: has been.", "Опыт → present perfect: has been."),
      P("'last night' → past simple: saw.", "'last night' → past simple: saw."),
      P("Hozirgi natija → has lost.", "Результат сейчас → has lost."),
      P("'in 2015' → past simple: moved.", "'in 2015' → past simple: moved."),
      P("Tajriba savoli → Have you ever ridden?", "Вопрос об опыте → Have you ever ridden?"),
      P("'two days ago' → past simple: met.", "'two days ago' → past simple: met."),
      P("'already' + hozirgi natija → has left.", "'already' + результат сейчас → has left."),
      P("'for ten years' davom etyapti → have lived.", "'for ten years' продолжается → have lived."),
      P("'last night' → past simple: did you arrive?", "'last night' → past simple: did you arrive?"),
      P("'last week' past simple'ni talab qiladi: I saw her last week.", "'last week' требует past simple: I saw her last week."),
      P("Davomiy 'have known' + tugagan voqea 'met' (2010-yilda).", "Продолжающееся 'have known' + завершённое 'met' (в 2010)."),
      P("Tajriba → Have you ever been…?", "Опыт → Have you ever been…?"),
      P("'this year' (tugamagan) → has read; 'last weekend' → read.", "'this year' (не закончен) → has read; 'last weekend' → read."),
      P("Present perfect hozirgi natijani ko'rsatadi: I've broken my arm.", "Present perfect показывает результат сейчас: I've broken my arm."),
    ],
  },
  g10: {
    situation: P("“Men tennis o'ynardim, lekin yillar oldin tashladim.” — used to endi mavjud bo'lmagan o'tmish odati yoki holatini bildiradi.", "«Я раньше играл в теннис, но бросил много лет назад.» — used to описывает прошлую привычку или состояние, которых больше нет."),
    tip: P("Inkor va savollarda '-d' tushib qoladi: 'didn't use to' va 'Did you use to…?', hech qachon 'didn't used to' emas.", "В отрицаниях и вопросах '-d' исчезает: 'didn't use to' и 'Did you use to…?', никогда 'didn't used to'."),
    blocks: [
      { h: P("O'tmish odatlari va holatlari", "Прошлые привычки и состояния"), p: [P("used to + asosiy fe'l: o'tmishda muntazam bo'lgan ish yoki avval to'g'ri bo'lib, endi bo'lmagan holat.", "used to + начальная форма: регулярное действие в прошлом или состояние, которое было, а теперь нет.")] },
      { h: P("Inkor va savollar", "Отрицания и вопросы"), p: [P("Inkor: didn't use to (-d siz). Savol: Did … use to…?", "Отрицание: didn't use to (без -d). Вопрос: Did … use to…?")] },
      { h: P("used to va hozirgi zamon", "used to и настоящее"), p: [P("'used to' doim o'tmishni hozir bilan qarama-qarshi qo'yadi.", "'used to' всегда противопоставляет прошлое настоящему.")] },
      { h: P("Faqat o'tmish uchun", "Только для прошлого"), p: [P("Hozirgi odatlar uchun present simple ishlatiladi, 'used to' emas.", "Для нынешних привычек — present simple, а не 'used to'.")] },
    ],
    quiz: [
      P("O'tmish odati: used to play.", "Прошлая привычка: used to play."),
      P("O'tmish holati: used to live.", "Прошлое состояние: used to live."),
      P("O'tmish holati: used to have.", "Прошлое состояние: used to have."),
      P("O'tmish odati: used to go.", "Прошлая привычка: used to go."),
      P("O'tmish holati: used to be.", "Прошлое состояние: used to be."),
      P("Inkorда -d tushadi: didn't use to.", "В отрицании -d исчезает: didn't use to."),
      P("Savol: Did you use to…?", "Вопрос: Did you use to…?"),
      P("Inkor odati: didn't use to.", "Отрицание привычки: didn't use to."),
      P("O'tmish odati: used to play.", "Прошлая привычка: used to play."),
      P("Did + use to (-d siz): Did you use to smoke?", "Did + use to (без -d): Did you use to smoke?"),
      P("didn't dan keyin -d siz: didn't use to study.", "После didn't — без -d: didn't use to study."),
      P("O'tmish 'used to be' + hozirgi 'love'.", "Прошлое 'used to be' + настоящее 'love'."),
      P("Hozirgi odat uchun present simple: I run daily.", "Для нынешней привычки — present simple: I run daily."),
      P("Did + use to: Did they use to live…?", "Did + use to: Did they use to live…?"),
      P("'used to' o'tmish odatini hozir bilan solishtiradi (endi yo'q).", "'used to' противопоставляет прошлую привычку настоящему (теперь нет)."),
    ],
  },
  g11: {
    situation: null,
    tip: P("Ehtiyot bo'ling: mustn't va don't have to butunlay boshqa. 'You mustn't go' = borish TAQIQLANGAN. 'You don't have to go' = xohlasangiz qolishingiz mumkin.", "Осторожно: mustn't и don't have to — совершенно разное. 'You mustn't go' = идти ЗАПРЕЩЕНО. 'You don't have to go' = можно остаться, если хотите."),
    blocks: [
      { h: P("must va have to (majburiyat)", "must и have to (обязанность)"), p: [P("must va have to + asosiy fe'l — zarurat. 'Must' ko'proq so'zlovchidan, 'have to' tashqi qoidalardan kelib chiqadi.", "must и have to + начальная форма — необходимость. 'Must' чаще от говорящего, 'have to' — от внешних правил.")] },
      { h: P("should (maslahat)", "should (совет)"), p: [P("should + asosiy fe'l maslahat yoki eng to'g'ri ish haqidagi fikrni bildiradi.", "should + начальная форма — совет или мнение о лучшем действии.")] },
      { h: P("mustn't va don't have to", "mustn't и don't have to"), p: [P("mustn't = taqiqlangan (qilmang!). don't have to = shart emas (lekin mumkin).", "mustn't = запрещено (не делайте!). don't have to = не обязательно (но можно).")] },
      { h: P("O'tmish: had to", "Прошлое: had to"), p: [P("'must' va 'have to'ning o'tmishi — had to.", "Прошедшее от 'must' и 'have to' — had to.")] },
    ],
    quiz: [
      P("Majburiyat/qoida → have to.", "Обязанность/правило → have to."),
      P("Maslahat → should.", "Совет → should."),
      P("Taqiq → mustn't.", "Запрет → mustn't."),
      P("Zarurat → have to.", "Необходимость → have to."),
      P("Qilmaslik maslahati → shouldn't.", "Совет не делать → shouldn't."),
      P("Shart emas → don't have to.", "Не обязательно → don't have to."),
      P("Qat'iy qoida → must.", "Строгое правило → must."),
      P("O'tmish majburiyati → had to leave.", "Прошлая обязанность → had to leave."),
      P("Maslahat → should.", "Совет → should."),
      P("Taqiq → mustn't.", "Запрет → mustn't."),
      P("don't have to = shart emas (ixtiyoriy).", "don't have to = не обязательно (по желанию)."),
      P("'mustn't be late' (taqiq) + 'don't have to come' (ixtiyoriy).", "'mustn't be late' (запрет) + 'don't have to come' (по желанию)."),
      P("should + asosiy fe'l: You should study more.", "should + начальная форма: You should study more."),
      P("O'tmish majburiyati → had to (ikki marta).", "Прошлая обязанность → had to (дважды)."),
      P("Taqiq → mustn't park here.", "Запрет → mustn't park here."),
    ],
  },
  g12: {
    situation: P("“Agar ertaga yomg'ir yog'sa, uyda qolamiz.” — Birinchi shart gapi real, ehtimoliy kelajak natijasi haqida.", "«Если завтра пойдёт дождь, мы останемся дома.» — Первый кондиционал о реальном, вероятном будущем результате."),
    tip: P("If qismida 'will' ishlatmang: 'If it will rain' — xato → 'If it rains, we will stay home.' Shart present simple'da bo'ladi.", "Не используйте 'will' в if-части: 'If it will rain' — ошибка → 'If it rains, we will stay home.' Условие — в present simple."),
    blocks: [
      { h: P("Shakl: if + hozirgi, will + asosiy", "Форма: if + настоящее, will + начальная"), p: [P("If qismi present simple'da; natija qismi will + asosiy fe'l.", "If-часть в present simple; часть результата — will + начальная форма.")] },
      { h: P("Qismlar tartibi", "Порядок частей"), p: [P("Istalgan qismdan boshlash mumkin. Vergul faqat if qismi birinchi kelganda qo'yiladi.", "Можно начать с любой части. Запятая — только когда if-часть первая.")] },
      { h: P("unless", "unless"), p: [P("unless = 'agar … bo'lmasa'.", "unless = «если … не».")] },
      { h: P("Natijada may / might / can", "may / might / can в результате"), p: [P("'will' o'rniga may, might (ehtimol) yoki can (imkoniyat) ishlatish mumkin.", "Вместо 'will' можно may, might (возможно) или can (возможность).")] },
    ],
    quiz: [
      P("Natija qismi → will stay.", "Часть результата → will stay."),
      P("If qismi → present simple: study.", "If-часть → present simple: study."),
      P("If qismi → present simple: have.", "If-часть → present simple: have."),
      P("Natija → will catch.", "Результат → will catch."),
      P("If qismi → hozirgi: is.", "If-часть → настоящее: is."),
      P("If + hozirgi: leave.", "If + настоящее: leave."),
      P("'unless' = agar … bo'lmasa.", "'unless' = если … не."),
      P("If + hozirgi: pass.", "If + настоящее: pass."),
      P("Ehtimoliy natija → might go.", "Возможный результат → might go."),
      P("If + hozirgi, will + asosiy.", "If + настоящее, will + начальная."),
      P("If qismida 'will' yo'q: If you help me…", "В if-части нет 'will': If you help me…"),
      P("'won't pass unless you study' = agar o'qimasangiz.", "'won't pass unless you study' = если не будете заниматься."),
      P("If + hozirgi, will + asosiy fe'l.", "If + настоящее, will + начальная форма."),
      P("If + hozirgi (snows) + will + asosiy (will be).", "If + настоящее (snows) + will + начальная (will be)."),
      P("If qismi birinchi kelsa, undan keyin vergul.", "Если if-часть первая — после неё запятая."),
    ],
  },
  g13: {
    situation: null,
    tip: P("Odamlar uchun who, narsalar uchun which; that ikkalasini almashtira oladi. Ortiqcha olmosh qo'shmang: 'The man who he lives next door' — xato, 'he' olib tashlanadi.", "Для людей — who, для предметов — which; that заменяет оба. Не добавляйте лишнее местоимение: 'The man who he lives next door' — ошибка, 'he' убирается."),
    blocks: [
      { h: P("who (odamlar) va which (narsalar)", "who (люди) и which (предметы)"), p: [P("Odamlar uchun who, narsalar va hayvonlar uchun which.", "Для людей — who, для предметов и животных — which.")] },
      { h: P("that", "that"), p: [P("that ko'p gaplarda who yoki which o'rnini bosadi, ayniqsa og'zaki nutqda.", "that заменяет who или which во многих предложениях, особенно в речи.")] },
      { h: P("where (joylar)", "where (места)"), p: [P("Joy haqida gapirganda where ishlatiladi.", "О месте — where.")] },
      { h: P("whose (egalik)", "whose (принадлежность)"), p: [P("Biror narsa kimgadir tegishli ekanini ko'rsatish uchun whose.", "Чтобы показать принадлежность — whose.")] },
    ],
    quiz: [
      P("Odamlar → who.", "Люди → who."),
      P("Narsalar → which.", "Предметы → which."),
      P("Joy → where.", "Место → where."),
      P("Egalik → whose.", "Принадлежность → whose."),
      P("Narsalar → that (yoki which).", "Предметы → that (или which)."),
      P("Odamlar → who.", "Люди → who."),
      P("Joy → where.", "Место → where."),
      P("Narsalar → which (yoki that).", "Предметы → which (или that)."),
      P("Odamlar → who (yoki that).", "Люди → who (или that)."),
      P("Odamlar → who.", "Люди → who."),
      P("Ortiqcha ega qo'shilmaydi: The man who lives next door…", "Лишнее подлежащее не добавляется: The man who lives next door…"),
      P("'whose bag' (egalik) + 'who called' (ega).", "'whose bag' (принадлежность) + 'who called' (подлежащее)."),
      P("Narsalar → which (yoki that).", "Предметы → which (или that)."),
      P("Joy 'where I was born' + narsa 'which is now closed'.", "Место 'where I was born' + предмет 'which is now closed'."),
      P("Narsalar → that ('a place that sells…').", "Предметы → that ('a place that sells…')."),
    ],
  },
  g14: {
    situation: null,
    tip: P("'because'dan keyin sabab, 'so'dan keyin natija keladi. 'I was tired because I worked late' = sabab; 'I worked late, so I was tired' = natija.", "После 'because' — причина, после 'so' — следствие. 'I was tired because I worked late' = причина; 'I worked late, so I was tired' = следствие."),
    blocks: [
      { h: P("because (sabab) va so (natija)", "because (причина) и so (следствие)"), p: [P("because sababni, so natijani kiritadi.", "because вводит причину; so — следствие.")] },
      { h: P("but va however (qarama-qarshilik)", "but и however (контраст)"), p: [P("but bitta gapda ikki zid fikrni bog'laydi; however ko'pincha yangi gapni boshlaydi.", "but соединяет два контраста в одном предложении; however часто начинает новое.")] },
      { h: P("although / though", "although / though"), p: [P("although gap ichida kutilmagan qarama-qarshilikni kiritadi.", "although вводит неожиданный контраст внутри предложения.")] },
      { h: P("and / or / also", "and / or / also"), p: [P("and qo'shadi; or tanlov beradi; also qo'shimcha ma'lumot kiritadi.", "and добавляет; or даёт выбор; also вводит дополнительное.")] },
    ],
    quiz: [
      P("Natija → so.", "Следствие → so."),
      P("Sabab → because.", "Причина → because."),
      P("Qarama-qarshilik → but.", "Контраст → but."),
      P("Tanlov → or.", "Выбор → or."),
      P("Qo'shish → and.", "Добавление → and."),
      P("Kutilmagan qarama-qarshilik → Although.", "Неожиданный контраст → Although."),
      P("Natija → so.", "Следствие → so."),
      P("Qarama-qarshilik → but.", "Контраст → but."),
      P("'because of' + ot (the bad weather).", "'because of' + существительное (the bad weather)."),
      P("Sabab → because.", "Причина → because."),
      P("'although' va 'but' birga ishlatilmaydi: Although it was late, we kept working.", "'although' и 'but' вместе не используются: Although it was late, we kept working."),
      P("Natija 'so I missed school' + qarama-qarshilik 'but I'm fine now'.", "Следствие 'so I missed school' + контраст 'but I'm fine now'."),
      P("Kutilmagan qarama-qarshilik → Although.", "Неожиданный контраст → Although."),
      P("Sabab 'because' + qo'shish 'and now she's a doctor'.", "Причина 'because' + добавление 'and now she's a doctor'."),
      P("Natija → so the roads closed.", "Следствие → so the roads closed."),
    ],
  },
  g15: {
    situation: null,
    tip: P("Tag yordamchi fe'lni takrorlaydi va musbat/manfiyni teskarisiga aylantiradi: 'He's here, isn't he?' / 'He isn't here, is he?'", "Хвостик повторяет вспомогательный глагол и меняет знак: 'He's here, isn't he?' / 'He isn't here, is he?'"),
    blocks: [
      { h: P("Musbat gap → manfiy tag", "Утверждение → отрицательный хвостик"), p: [P("Musbat gapdan keyin tag manfiy bo'ladi, o'sha yordamchi fe'l bilan.", "После утверждения хвостик отрицательный, с тем же вспомогательным глаголом.")] },
      { h: P("Manfiy gap → musbat tag", "Отрицание → положительный хвостик"), p: [P("Manfiy gapdan keyin tag musbat bo'ladi.", "После отрицания хвостик положительный.")] },
      { h: P("Fe'lni moslashtirish", "Согласование глагола"), p: [P("'be' bilan 'be'; boshqa fe'llar bilan do/does/did; present perfect bilan have/has; modal bilan o'sha modal.", "С 'be' — 'be'; с другими глаголами do/does/did; с present perfect — have/has; с модальными — тот же модальный.")] },
      { h: P("Maxsus holatlar", "Особые случаи"), p: [P("'I am' → tag: aren't I. 'Let's…' → tag: shall we.", "'I am' → хвостик aren't I. 'Let's…' → хвостик shall we.")] },
    ],
    quiz: [
      P("Musbat gap → manfiy tag: aren't you?", "Утверждение → отрицательный хвостик: aren't you?"),
      P("Present simple musbat → doesn't she?", "Present simple утверждение → doesn't she?"),
      P("Manfiy gap → musbat tag: are they?", "Отрицание → положительный хвостик: are they?"),
      P("Modal 'can' → can't he?", "Модальный 'can' → can't he?"),
      P("Manfiy → musbat tag: do you?", "Отрицание → положительный: do you?"),
      P("'be' musbat → isn't she?", "'be' утверждение → isn't she?"),
      P("Past simple musbat → didn't they?", "Past simple утверждение → didn't they?"),
      P("Present perfect musbat → haven't you?", "Present perfect утверждение → haven't you?"),
      P("Manfiy 'won't' → musbat tag: will he?", "Отрицание 'won't' → положительный: will he?"),
      P("'Let's…' → shall we?", "'Let's…' → shall we?"),
      P("'I am'ning maxsus tagi: 'aren't I?'", "Особый хвостик для 'I am': 'aren't I?'"),
      P("Manfiy o'tmish → musbat tag: did she?", "Отрицание в прошлом → положительный: did she?"),
      P("Musbat modal → manfiy tag: can't you?", "Утверждение с модальным → отрицательный: can't you?"),
      P("Present perfect musbat → haven't they?", "Present perfect утверждение → haven't they?"),
      P("'there is' bilan tag: 'isn't there?'", "С 'there is' хвостик: 'isn't there?'"),
    ],
  },
};
