// Full B1 grammar translations (g9–g15) — situation, tip, blocks, quiz explanations.
const P = (uz, ru) => ({ uz, ru });
export const B1_TR_2 = {
  g9: {
    situation: null,
    tip: P("Vergul faqat qo'shimcha ma'lumot (non-defining) uchun qo'yiladi. Vergul bilan hech qachon 'that' ishlatmang va olmoshni tushirib qoldirmang. Vergulsiz (defining) 'that' ishlatish va to'ldiruvchi olmoshini tushirish mumkin.", "Запятые ставятся только при дополнительной информации (non-defining). С запятыми нельзя «that» и нельзя опускать местоимение. Без запятых (defining) можно «that» и можно опустить местоимение-дополнение."),
    blocks: [
      { h: P("Aniqlovchi (defining) gaplar", "Определительные (defining) придаточные"), p: [P("Zaruriy ma'lumot beradi (qaysi odam yoki narsa ekanini bilish uchun kerak). who, which, that, where, whose ishlatiladi. Vergul yo'q.", "Дают необходимую информацию (без неё не ясно, о ком или о чём речь). Используются who, which, that, where, whose. Без запятых.")] },
      { h: P("Qo'shimcha (non-defining) gaplar", "Неопределительные (non-defining) придаточные"), p: [P("Qo'shimcha, zaruriy bo'lmagan ma'lumot beradi, vergul bilan ajratiladi. 'that' ishlatilmaydi; olmosh tushirilmaydi.", "Дают дополнительную, необязательную информацию, выделяются запятыми. Нельзя «that»; нельзя опускать местоимение.")] },
      { h: P("Olmoshni tushirib qoldirish", "Опущение местоимения"), p: [P("Defining gaplarda who/which/that to'ldiruvchi bo'lsa, uni tushirib qoldirish mumkin.", "В defining-придаточных who/which/that можно опустить, если это дополнение.")] },
      { h: P("whose va where", "whose и where"), p: [P("whose egalikni bildiradi; where joyga ishora qiladi.", "whose показывает принадлежность; where относится к месту.")] },
    ],
    quiz: [
      P("Odamlar → who.", "Люди → who."),
      P("Narsalar → which/that.", "Предметы → which/that."),
      P("Joy → where.", "Место → where."),
      P("Egalik → whose.", "Принадлежность → whose."),
      P("Non-defining → vergul.", "Non-defining → запятые."),
      P("Defining gapdagi to'ldiruvchi olmoshi tushiriladi: the book I read.", "Местоимение-дополнение в defining можно опустить: the book I read."),
      P("Non-defining narsalar → which (hech qachon 'that' emas).", "Non-defining для предметов → which (никогда «that»)."),
      P("Narsalar → which/that.", "Предметы → which/that."),
      P("Non-defining odamlar → who.", "Non-defining для людей → who."),
      P("Defining = zaruriy, vergulsiz.", "Defining = необходимая информация, без запятых."),
      P("Non-defining gaplarda 'which' ishlatiladi, 'that' emas.", "В non-defining используется «which», а не «that»."),
      P("Joy 'where we stayed' + non-defining 'which was by the sea'.", "Место «where we stayed» + non-defining «which was by the sea»."),
      P("To'ldiruvchi olmoshi tushirilgan: the film (that) we saw.", "Опущено местоимение-дополнение: the film (that) we saw."),
      P("'whose goal' (egalik) + non-defining 'which made him famous'.", "«whose goal» (принадлежность) + non-defining «which made him famous»."),
      P("Qo'shimcha ma'lumot → vergul + who.", "Дополнительная информация → запятые + who."),
    ],
  },
  g10: {
    situation: null,
    tip: P("'would' faqat takrorlangan harakatlar uchun. O'tgan holatlar (be, have, like, know) uchun faqat 'used to': 'I used to have a bike', 'I would have a bike' emas.", "«would» — только для повторявшихся действий. Для состояний в прошлом (be, have, like, know) нужно «used to»: «I used to have a bike», а не «I would have a bike»."),
    blocks: [
      { h: P("used to (odatlar va holatlar)", "used to (привычки и состояния)"), p: [P("used to + asosiy shakl — endi mavjud bo'lmagan o'tgan odatlar va holatlarni bildiradi.", "used to + начальная форма описывает прошлые привычки и состояния, которых больше нет.")] },
      { h: P("would (faqat takroriy odatlar)", "would (только повторявшиеся действия)"), p: [P("would + asosiy shakl — takrorlangan o'tgan harakatlarni bildiradi, holatlarni emas. Hikoyalarda ko'p uchraydi.", "would + начальная форма описывает повторявшиеся действия в прошлом, но не состояния. Часто в рассказах.")] },
      { h: P("Holatlar bilan would va used to", "would и used to с состояниями"), p: [P("Holat fe'llari (be, have, like, know) bilan 'would' ishlatmang. 'used to' ishlating.", "С глаголами состояния (be, have, like, know) нельзя «would». Используйте «used to».")] },
      { h: P("Inkor va savollar", "Отрицания и вопросы"), p: [P("'used to' uchun: didn't use to / Did … use to? (-d siz).", "Для «used to»: didn't use to / Did … use to? (без -d).")] },
    ],
    quiz: [
      P("O'tgan odat: used to play.", "Прошлая привычка: used to play."),
      P("Takrorlangan harakat → would go.", "Повторявшееся действие → would go."),
      P("O'tgan holat → used to have.", "Прошлое состояние → used to have."),
      P("Takrorlangan harakat → would visit.", "Повторявшееся действие → would visit."),
      P("O'tgan holat → used to be.", "Прошлое состояние → used to be."),
      P("'would' holat fe'li 'be' bilan ishlatilmaydi.", "«would» нельзя с глаголом состояния «be»."),
      P("didn't use to (-d siz).", "didn't use to (без -d)."),
      P("Takrorlangan harakat → would swim.", "Повторявшееся действие → would swim."),
      P("Did you use to…?", "Did you use to…?"),
      P("'have' — holat → used to have.", "«have» — состояние → used to have."),
      P("Holat 'have' → used to have ('would' emas).", "Состояние «have» → used to have (не would)."),
      P("Takroriy harakat 'would tell' + holat 'used to have'.", "Повторявшееся действие «would tell» + состояние «used to have»."),
      P("Holat 'used to be' + takroriy harakat 'would smoke'.", "Состояние «used to be» + повторявшееся действие «would smoke»."),
      P("Did + use to: Did they use to live…?", "Did + use to: Did they use to live…?"),
      P("Holat 'have' → used to have.", "Состояние «have» → used to have."),
    ],
  },
  g11: {
    situation: null,
    tip: P("Predloglardan keyin (about, of, at, in, before, after, without) doim -ing shakli: 'I'm interested in learning', 'before going out'.", "После предлогов (about, of, at, in, before, after, without) всегда форма -ing: «I'm interested in learning», «before going out»."),
    blocks: [
      { h: P("Fe'l + -ing", "Глагол + -ing"), p: [P("enjoy, finish, avoid, suggest, mind, keep, practise, can't stand, look forward to dan keyin va predloglardan keyin -ing shakli ishlatiladi.", "После enjoy, finish, avoid, suggest, mind, keep, practise, can't stand, look forward to и после предлогов — форма -ing.")] },
      { h: P("Fe'l + to-infinitiv", "Глагол + to-инфинитив"), p: [P("want, decide, hope, plan, promise, agree, offer, refuse, manage, learn, would like dan keyin to + fe'l ishlatiladi.", "После want, decide, hope, plan, promise, agree, offer, refuse, manage, learn, would like — to + глагол.")] },
      { h: P("Fe'l + to'ldiruvchi + to", "Глагол + дополнение + to"), p: [P("Ba'zi fe'llar to'ldiruvchi, keyin to-infinitiv oladi: want, ask, tell, allow, advise, expect.", "Некоторые глаголы берут дополнение, затем to-инфинитив: want, ask, tell, allow, advise, expect.")] },
      { h: P("Ma'no o'zgarishi", "Изменение значения"), p: [P("Ayrim fe'llarda ma'no o'zgaradi: stop, remember, try, forget.", "У нескольких глаголов значение меняется: stop, remember, try, forget.")] },
    ],
    quiz: [
      P("enjoy + -ing: listening.", "enjoy + -ing: listening."),
      P("decide + to: to leave.", "decide + to: to leave."),
      P("'at' predlogi + -ing: drawing.", "Предлог «at» + -ing: drawing."),
      P("refuse + to: to answer.", "refuse + to: to answer."),
      P("mind + -ing: opening.", "mind + -ing: opening."),
      P("ask + to'ldiruvchi + to: to help.", "ask + дополнение + to: to help."),
      P("'about' predlogi + -ing: buying.", "Предлог «about» + -ing: buying."),
      P("manage + to: to solve.", "manage + to: to solve."),
      P("'look forward to' + -ing: seeing.", "«look forward to» + -ing: seeing."),
      P("suggest + -ing: taking.", "suggest + -ing: taking."),
      P("'in' predlogi + -ing: learning.", "Предлог «in» + -ing: learning."),
      P("stop + to = biror ish qilish uchun to'xtamoq.", "stop + to = остановиться, чтобы что-то сделать."),
      P("remember to do (vazifa) + forget doing (xotira).", "remember to do (обязанность) + forget doing (воспоминание)."),
      P("allow + to'ldiruvchi + to: allowed us to stay.", "allow + дополнение + to: allowed us to stay."),
      P("try to do (urinish) + try doing (tajriba): to open / using.", "try to do (попытка) + try doing (эксперимент): to open / using."),
    ],
  },
  g12: {
    situation: null,
    tip: P("Qiyosiy darajani kuchaytirish uchun much yoki far ishlatiladi (much/far better), 'very' emas. 'Very better' — xato; 'much better' — to'g'ri.", "Чтобы усилить сравнительную степень, используйте much или far (much/far better), а не «very». «Very better» — ошибка; «much better» — верно."),
    blocks: [
      { h: P("as … as (tenglik)", "as … as (равенство)"), p: [P("Ikki narsa bir xil ekanini aytish uchun as + sifat + as, tengsizlik uchun not as … as ishlatiladi.", "as + прилагательное + as — когда две вещи одинаковы; not as … as — при неравенстве.")] },
      { h: P("less … than", "less … than"), p: [P("less + sifat + than ('more … than' ning teskarisi), odatda uzun sifatlar bilan ishlatiladi.", "less + прилагательное + than (противоположность «more … than»), обычно с длинными прилагательными.")] },
      { h: P("Kuchaytiruvchi so'zlar", "Усилители"), p: [P("Qiyosiy darajani much, far, a lot, a bit, slightly bilan kuchaytirish yoki yumshatish mumkin.", "Сравнительную степень усиливают или смягчают: much, far, a lot, a bit, slightly.")] },
      { h: P("the … the … (parallel)", "the … the … (параллельное сравнение)"), p: [P("Ikki narsa birga o'zgarishini ko'rsatish uchun 'the + qiyosiy … the + qiyosiy' ishlatiladi.", "«the + сравнительная … the + сравнительная» показывает, что две вещи меняются вместе.")] },
    ],
    quiz: [
      P("Tenglik: as tall as.", "Равенство: as tall as."),
      P("not as cold as.", "not as cold as."),
      P("less interesting than.", "less interesting than."),
      P("Kuchaytiruvchi → much taller.", "Усилитель → much taller."),
      P("'just a bit warmer' — just/a bit qiyosiy darajani yumshatadi.", "«just a bit warmer» — just/a bit смягчают сравнение."),
      P("Tenglik: as expensive as.", "Равенство: as expensive as."),
      P("less exciting than.", "less exciting than."),
      P("Kuchaytiruvchi → far better.", "Усилитель → far better."),
      P("the more … the better.", "the more … the better."),
      P("Tenglik → as tall as.", "Равенство → as tall as."),
      P("'much better' ishlatiladi, 'very better' emas.", "Нужно «much better», а не «very better»."),
      P("not as difficult as.", "not as difficult as."),
      P("as good as = teng.", "as good as = равны."),
      P("the sooner … the earlier.", "the sooner … the earlier."),
      P("far cheaper (much/far + qiyosiy daraja).", "far cheaper (much/far + сравнительная степень)."),
    ],
  },
  g13: {
    situation: null,
    tip: P("every va each dan keyin birlikdagi ot va fe'l keladi: 'Every student is here', 'every students are here' emas.", "После every и each — существительное и глагол в единственном числе: «Every student is here», а не «every students are here»."),
    blocks: [
      { h: P("all / most / some / none", "all / most / some / none"), p: [P("Umumiy miqdorlar uchun ishlatiladi. 'the/my/these' + ot bilan of qo'shiladi: most of the students.", "Для общих количеств. С «the/my/these» + существительное добавляется of: most of the students.")] },
      { h: P("both / neither / either", "both / neither / either"), p: [P("both = ikkalasi birga; neither = na u, na bu; either = u yoki bu.", "both = оба вместе; neither = ни тот, ни другой; either = тот или другой.")] },
      { h: P("each va every", "each и every"), p: [P("Ikkalasi ham 'hammasi, alohida-alohida' ma'nosini beradi va birlikdagi fe'l oladi. 'every' — butun guruh uchun; 'each' — har biri uchun.", "Оба означают «все, по отдельности» и требуют глагол в единственном числе. «every» — о группе целиком; «each» — о каждом в отдельности.")] },
      { h: P("a few / a little / several", "a few / a little / several"), p: [P("a few + sanaladigan, a little + sanalmaydigan, several = bir nechtadan ko'proq (sanaladigan).", "a few + исчисляемые, a little + неисчисляемые, several = больше, чем несколько (исчисляемые).")] },
    ],
    quiz: [
      P("Umumiy → Most people.", "Общее → Most people."),
      P("'the' bilan → Most of the students.", "С «the» → Most of the students."),
      P("Ikkalasi birga → Both answers.", "Оба вместе → Both answers."),
      P("+ birlikdagi ot → Every student.", "+ существительное в ед. числе → Every student."),
      P("Sanalmaydigan → a little.", "Неисчисляемое → a little."),
      P("Nol → None of the answers.", "Ноль → None of the answers."),
      P("Na u, na bu → Neither.", "Ни тот, ни другой → Neither."),
      P("Har biri + birlik → Each child.", "Каждый + ед. число → Each child."),
      P("Bir nechtadan ko'proq, sanaladigan → Several.", "Больше, чем несколько, исчисляемое → Several."),
      P("'every' → birlik: is.", "«every» → ед. число: is."),
      P("every + birlik: Every student is present.", "every + ед. число: Every student is present."),
      P("Either of the two is fine; choose either.", "Either of the two is fine; choose either."),
      P("Umumiy gap → Most people (the/my/these siz 'of' yo'q).", "Общее утверждение → Most people (без «of», если нет the/my/these)."),
      P("All of my friends came, but none stayed late.", "All of my friends came, but none stayed late."),
      P("'each' → birlikdagi fe'l: has.", "«each» → глагол в ед. числе: has."),
    ],
  },
  g14: {
    situation: null,
    tip: P("if/unless/as long as/in case dan keyin shart qismida 'will' ishlatmang: 'If it will rain' — xato → 'If it rains, we'll stay in.'", "Не используйте «will» в условии после if/unless/as long as/in case: «If it will rain» — ошибка → «If it rains, we'll stay in»."),
    blocks: [
      { h: P("Zero conditional (faktlar)", "Zero conditional (факты)"), p: [P("Doim to'g'ri bo'lgan narsalar uchun if/when + hozirgi, hozirgi zamon ishlatiladi.", "Для всегда верных вещей: if/when + настоящее, настоящее.")] },
      { h: P("First conditional (ehtimoli katta kelajak)", "First conditional (вероятное будущее)"), p: [P("Real, ehtimoli katta kelajak vaziyatlar uchun if + hozirgi, will + asosiy shakl.", "Для реальных, вероятных будущих ситуаций: if + настоящее, will + начальная форма.")] },
      { h: P("unless", "unless"), p: [P("unless = if … not. U natijani o'zgartiradigan yagona shartni kiritadi.", "unless = if … not. Вводит единственное условие, меняющее результат.")] },
      { h: P("as long as / provided that / in case", "as long as / provided that / in case"), p: [P("as long as / provided that = shu shart bilan; in case = ehtiyot chorasi sifatida.", "as long as / provided that = при условии, что; in case = на всякий случай.")] },
    ],
    quiz: [
      P("Zero conditional → hozirgi zamon: melts.", "Zero conditional → настоящее: melts."),
      P("First conditional → will stay.", "First conditional → will stay."),
      P("unless = if … not.", "unless = if … not."),
      P("Zero conditional → hozirgi zamon: heat.", "Zero conditional → настоящее: heat."),
      P("'when I arrive' (bo'lishi aniq).", "«when I arrive» (это точно произойдёт)."),
      P("Ehtiyot chorasi → in case it gets cold.", "Предосторожность → in case it gets cold."),
      P("Shart → as long as.", "Условие → as long as."),
      P("First conditional → leave (hozirgi zamon).", "First conditional → leave (настоящее)."),
      P("unless = if … not.", "unless = if … not."),
      P("Umumiy fakt → zero conditional.", "Общий факт → zero conditional."),
      P("Shart qismida 'will' bo'lmaydi: as long as you ask.", "В условии нет «will»: as long as you ask."),
      P("Shart → provided that you give it back.", "Условие → provided that you give it back."),
      P("unless o'zi 'if not' ma'nosini beradi: Unless you hurry…", "unless уже означает «если не»: Unless you hurry…"),
      P("Ehtiyot chorasi → in case you get lost.", "Предосторожность → in case you get lost."),
      P("If + hozirgi zamon, will + asosiy shakl.", "If + настоящее, will + начальная форма."),
    ],
  },
  g15: {
    situation: null,
    tip: P("Yangi yoki ko'pdan biri bo'lsa — a/an; aniq yoki ma'lum bo'lsa — the. Ko'plik/sanalmaydigan otlar bilan umumiy gaplarda artikl ishlatilmaydi: 'Books are useful', 'The books are useful' emas.", "Новое или одно из многих — a/an; конкретное или известное — the. В общих утверждениях с множественным числом и неисчисляемыми — без артикля: «Books are useful», а не «The books are useful»."),
    blocks: [
      { h: P("a / an (ko'pdan biri, yangi)", "a / an (одно из многих, новое)"), p: [P("Birinchi marta tilga olingan yoki misol sifatida keltirilgan birlikdagi sanaladigan otlar bilan a/an ishlatiladi. Unli tovushdan oldin 'an'.", "a/an — с исчисляемыми существительными в ед. числе, упомянутыми впервые или как пример. Перед гласным звуком — «an».")] },
      { h: P("the (aniq / ma'lum)", "the (конкретное / известное)"), p: [P("So'zlovchi ham, tinglovchi ham qaysi biri ekanini bilsa, yagona narsalar uchun va qayta tilga olinganda the ishlatiladi.", "the — когда и говорящий, и слушатель знают, о чём речь, для уникальных вещей и при повторном упоминании.")] },
      { h: P("Nol artikl (umumiy)", "Нулевой артикль (общее)"), p: [P("Umumiy ma'nodagi ko'plik va sanalmaydigan otlar bilan, ko'pchilik nomlar, taomlar va ko'p joylar bilan artikl ishlatilmaydi.", "Без артикля — множественное число и неисчисляемые в общем значении, большинство имён, приёмы пищи и многие места.")] },
      { h: P("Turg'un iboralar", "Устойчивые выражения"), p: [P("Ba'zi joylar an'anaga ko'ra 'the' yoki nol artikl oladi.", "Некоторые места по традиции берут «the» или нулевой артикль.")] },
    ],
    quiz: [
      P("Yangi, birlikdagi sanaladigan → a cat.", "Новое, ед. число, исчисляемое → a cat."),
      P("h talaffuz qilinmaydi, unli tovush → an honest.", "Немая h, гласный звук → an honest."),
      P("Yagona narsa → The sun.", "Уникальный объект → The sun."),
      P("Umumiy sanalmaydigan → artiklsiz.", "Общее неисчисляемое → без артикля."),
      P("Unli tovush → an engineer.", "Гласный звук → an engineer."),
      P("Turg'un ibora → go to bed (nol artikl).", "Устойчивое выражение → go to bed (нулевой артикль)."),
      P("Qayta tilga olingan → The phone.", "Повторное упоминание → The phone."),
      P("Umumiy ko'plik → artiklsiz.", "Общее множественное → без артикля."),
      P("Cholg'u asboblari → play the violin.", "Музыкальные инструменты → play the violin."),
      P("h talaffuz qilinmaydi → an hour.", "Немая h → an hour."),
      P("Umumiy sanalmaydigan → artiklsiz: I love nature.", "Общее неисчисляемое → без артикля: I love nature."),
      P("Taomlar va 'go to work' → nol artikl.", "Приёмы пищи и «go to work» → нулевой артикль."),
      P("Umumiy mavhum ot → artiklsiz: Life is hard.", "Общее абстрактное существительное → без артикля: Life is hard."),
      P("a film (yangi) / The film (ma'lum) / space (umumiy, nol artikl).", "a film (новое) / The film (известное) / space (общее, нулевой артикль)."),
      P("Orttirma daraja 'the' talab qiladi: the best doctor.", "Превосходная степень требует «the»: the best doctor."),
    ],
  },
};
