// Full B1 grammar translations (g1–g8) — situation, tip, blocks, quiz explanations.
const P = (uz, ru) => ({ uz, ru });
export const B1_TR_1 = {
  g1: {
    situation: null,
    tip: P("Holat fe'llari (know, like, be, have = egalik) bilan continuous ishlatmang: 'I have known her for years' deyiladi, 'I have been knowing' emas.", "Не используйте continuous с глаголами состояния (know, like, be, have = владеть): «I have known her for years», а не «I have been knowing»."),
    blocks: [
      { h: P("Shakl: have/has been + -ing", "Форма: have/has been + -ing"), p: [P("have/has been + fe'l-ing ishlatiladi. U tugallangan natijaga emas, harakat jarayonining o'ziga urg'u beradi.", "have/has been + глагол-ing. Акцент на самом процессе, а не на завершённом результате.")] },
      { h: P("for va since", "for и since"), p: [P("for + davr va since + boshlanish nuqtasi — harakat qancha vaqt davom etganini ko'rsatadi.", "for + период и since + точка отсчёта показывают, как долго длится действие.")] },
      { h: P("Continuous va simple", "Continuous и simple"), p: [P("Continuous qancha vaqt / qanchalik faol bo'lganini ta'kidlaydi; simple esa tugallangan natijani.", "Continuous подчёркивает длительность и активность; simple — завершённый результат.")] },
      { h: P("Yaqindagi harakat va natija", "Недавняя активность с результатом"), p: [P("U yaqinda bo'lgan harakat keltirib chiqargan hozirgi vaziyatni tushuntirishi mumkin.", "Может объяснять текущую ситуацию, вызванную недавней активностью.")] },
    ],
    quiz: [
      P("Davom etayotgan harakat + muddat → have been working.", "Длящееся действие + срок → have been working."),
      P("Hali davom etmoqda → has been studying.", "Всё ещё продолжается → has been studying."),
      P("Davom etayotgan holatning muddati → have you been living.", "Длительность продолжающейся ситуации → have you been living."),
      P("Hozirgi natijaga ega harakat → has been raining.", "Действие с результатом сейчас → has been raining."),
      P("Harakat muddati → have been playing.", "Длительность действия → have been playing."),
      P("Qancha davom etganiga urg'u → have been waiting.", "Акцент на длительности → have been waiting."),
      P("Holatni tushuntiruvchi yaqindagi harakat → have you been doing.", "Недавняя активность объясняет состояние → have you been doing."),
      P("Ikkalasi ham mumkin, lekin 'since' + davom etayotgan holat bilan continuous tabiiyroq: has been living.", "Оба возможны, но с «since» + продолжающейся ситуацией естественнее continuous: has been living."),
      P("'know' — holat fe'li → continuous da ishlatilmaydi.", "«know» — глагол состояния → не употребляется в continuous."),
      P("Yaqinda davom etgan harakat → have been staring.", "Недавнее длящееся действие → have been staring."),
      P("Holat fe'li: I have known him for years.", "Глагол состояния: I have known him for years."),
      P("Natijani tushuntiruvchi davomli harakat → has been baking.", "Длительное действие, объясняющее результат → has been baking."),
      P("Son bilan tugallangan natija → present perfect simple: I've written three emails.", "Завершённый результат с числом → present perfect simple: I've written three emails."),
      P("Davom etayotgan holat + davr → have been living for ten years.", "Продолжается + период → have been living for ten years."),
      P("Davom etayotgan kutish muddati → have you been waiting.", "Длительность продолжающегося ожидания → have you been waiting."),
    ],
  },
  g2: {
    situation: null,
    tip: P("Past perfect faqat bir o'tgan voqea boshqasidan oldin bo'lganini ko'rsatish kerak bo'lganda ishlatiladi. Oddiy ketma-ketlik uchun (avval… keyin…) past simple ning o'zi yetarli.", "Past perfect нужен только чтобы показать, что одно событие в прошлом произошло раньше другого. Для простой последовательности (сначала… потом…) достаточно past simple."),
    blocks: [
      { h: P("Shakl: had + sifatdosh", "Форма: had + причастие"), p: [P("Ikki o'tgan harakatdan oldingisi uchun had + fe'lning 3-shakli ishlatiladi.", "Для более раннего из двух прошлых действий: had + 3-я форма глагола.")] },
      { h: P("Past simple bilan", "С past simple"), p: [P("Ko'pincha past simple bilan birga keladi: past perfect — oldingi harakat, past simple — keyingisi.", "Часто идёт вместе с past simple: past perfect — более раннее действие, past simple — более позднее.")] },
      { h: P("after, before, when, by the time", "after, before, when, by the time"), p: [P("Ketma-ketlikni ko'rsatish uchun shu vaqt bog'lovchilari bilan ko'p ishlatiladi.", "Часто употребляется с этими временными союзами для показа последовательности.")] },
      { h: P("Inkor va savollar", "Отрицания и вопросы"), p: [P("Inkor: hadn't + sifatdosh. Savol: Had + ega + sifatdosh?", "Отрицание: hadn't + причастие. Вопрос: Had + подлежащее + причастие?")] },
    ],
    quiz: [
      P("Oldinroq bo'lgan harakat → had already left.", "Более раннее действие → had already left."),
      P("Oldingi harakat → had finished.", "Более раннее действие → had finished."),
      P("had + sifatdosh: had seen.", "had + причастие: had seen."),
      P("Oldingi harakat → had started.", "Более раннее действие → had started."),
      P("had + sifatdosh: had eaten.", "had + причастие: had eaten."),
      P("Oldingi harakat → had met.", "Более раннее действие → had met."),
      P("Birinchi harakat → had written.", "Первое действие → had written."),
      P("had + sifatdosh: had begun.", "had + причастие: had begun."),
      P("Past perfect savoli: Had you been?", "Вопрос в past perfect: Had you been?"),
      P("Qo'ng'iroqdan oldin → had gone out.", "До звонка → had gone out."),
      P("eat fe'lining sifatdoshi — eaten: had eaten.", "Причастие от eat — eaten: had eaten."),
      P("Oldingi harakat → had escaped.", "Более раннее действие → had escaped."),
      P("Oldingi 'had left' + keyingi 'arrived'.", "Раннее «had left» + позднее «arrived»."),
      P("O'zgarish oldinroq bo'lgan → had changed.", "Изменение произошло раньше → had changed."),
      P("Ovqat mehmonlar kelishidan oldin pishgan → had cooked.", "Ужин был готов до прихода гостей → had cooked."),
    ],
  },
  g3: {
    situation: null,
    tip: P("Reja uchun 'going to'; vaqti belgilangan kelishuv uchun present continuous; jadval uchun present simple; shu zahoti qabul qilingan qaror uchun 'will'.", "Для плана — «going to»; для договорённости со временем — present continuous; для расписания — present simple; для мгновенного решения — «will»."),
    blocks: [
      { h: P("will va be going to", "will и be going to"), p: [P("will = bashorat, shu zahoti qaror, taklif, va'da. be going to = reja/niyat va dalilga asoslangan bashorat.", "will = предсказания, мгновенные решения, предложения, обещания. be going to = планы/намерения и предсказания по признакам.")] },
      { h: P("Present continuous (kelishuvlar)", "Present continuous (договорённости)"), p: [P("Qat'iy kelishuvlar uchun present continuous ishlatiladi, odatda vaqt va boshqa odam bilan.", "Present continuous — для твёрдых договорённостей, обычно с указанием времени и другого человека.")] },
      { h: P("Present simple (jadvallar)", "Present simple (расписания)"), p: [P("Jadval bo'yicha voqealar uchun (transport, dasturlar, jadvallar) present simple ishlatiladi.", "Present simple — для событий по расписанию (транспорт, программы, графики).")] },
      { h: P("may / might (ehtimollik)", "may / might (возможность)"), p: [P("Mumkin, lekin aniq bo'lmagan narsalar uchun may/might ishlatiladi.", "may/might — для возможных, но не точных событий.")] },
    ],
    quiz: [
      P("Dalilga asoslangan bashorat → is going to crash.", "Предсказание по признакам → is going to crash."),
      P("Jadval → present simple: leaves.", "Расписание → present simple: leaves."),
      P("Qat'iy kelishuv → present continuous.", "Твёрдая договорённость → present continuous."),
      P("Shu zahoti qaror → will.", "Мгновенное решение → will."),
      P("Ehtimollik → might.", "Возможность → might."),
      P("Reja → are going to visit.", "План → are going to visit."),
      P("Jadval bo'yicha → present simple: starts.", "По расписанию → present simple: starts."),
      P("Vaqtli kelishuv → present continuous.", "Договорённость со временем → present continuous."),
      P("Taklif / shu zahoti qaror → will.", "Предложение / мгновенное решение → will."),
      P("Hozirgi dalil → is going to.", "Признаки сейчас → is going to."),
      P("Jadval → present simple: arrives.", "Расписание → present simple: arrives."),
      P("Reja → going to; bashorat → will.", "План → going to; предсказание → will."),
      P("Noaniq kelajak → might go.", "Неопределённое будущее → might go."),
      P("Jadval 'starts' + kelishuv 'are meeting'.", "Расписание «starts» + договорённость «are meeting»."),
      P("Qat'iy kelishuv → present continuous.", "Твёрдая договорённость → present continuous."),
    ],
  },
  g4: {
    situation: null,
    tip: P("Maslahat uchun 'If I were you, I'd…' — eng tabiiy ibora. Shakllarni aralashtirmang: 'If I would have money' — xato → 'If I had money, I would…'.", "Для совета естественна фраза «If I were you, I'd…». Не смешивайте формы: «If I would have money» — ошибка → «If I had money, I would…»."),
    blocks: [
      { h: P("Shakl: if + past simple, would + asosiy shakl", "Форма: if + past simple, would + начальная форма"), p: [P("Bu yerdagi o'tgan zamon o'tgan vaqtni bildirmaydi — u vaziyat faraziy ekanini ko'rsatadi.", "Прошедшее время здесь не означает прошлое — оно показывает, что ситуация гипотетическая.")] },
      { h: P("Hamma shaxslar uchun were", "were для всех лиц"), p: [P("'be' bilan ko'pincha hamma shaxslarda were ishlatiladi, ayniqsa 'If I were you' maslahatida.", "С «be» часто используется were для всех лиц, особенно в совете «If I were you».")] },
      { h: P("would / could / might", "would / could / might"), p: [P("'would' o'rniga could (qobiliyat/imkoniyat) yoki might (ehtimoliy natija) ishlatish mumkin.", "Вместо «would» можно использовать could (способность/возможность) или might (возможный результат).")] },
      { h: P("Birinchi va ikkinchi shart", "Первый и второй тип"), p: [P("First conditional = real/ehtimoli katta; second conditional = ehtimoli kam/noreal.", "First conditional = реальное/вероятное; second conditional = маловероятное/нереальное.")] },
    ],
    quiz: [
      P("Second conditional: if + o'tgan zamon (were).", "Second conditional: if + прошедшее (were)."),
      P("Natija → would help.", "Результат → would help."),
      P("Maslahat → If I were you.", "Совет → If I were you."),
      P("if + past simple: had.", "if + past simple: had."),
      P("Natija → would visit.", "Результат → would visit."),
      P("Faraziy → would you do.", "Гипотетическое → would you do."),
      P("if + past simple: studied.", "if + past simple: studied."),
      P("Natija → would buy.", "Результат → would buy."),
      P("Natijadagi qobiliyat → could drive.", "Способность в результате → could drive."),
      P("Ehtimoli kam / noreal → second conditional.", "Маловероятное/нереальное → second conditional."),
      P("If qismida 'would' bo'lmaydi: If I had money…", "В if-части нет «would»: If I had money…"),
      P("were (be) + would know.", "were (be) + would know."),
      P("If I were you, I would help.", "If I were you, I would help."),
      P("would win + played (o'tgan zamon).", "would win + played (прошедшее)."),
      P("If I were you, I'd take the job.", "If I were you, I'd take the job."),
    ],
  },
  g5: {
    situation: null,
    tip: P("'must be' (aniq shunday) ning teskarisi — 'can't be' (aniq unday emas), 'mustn't be' emas. 'Mustn't' taqiqni bildiradi, xulosani emas.", "Противоположность «must be» (точно так) — «can't be» (точно не так), а не «mustn't be». «Mustn't» — это запрет, а не вывод."),
    blocks: [
      { h: P("must (deyarli aniq)", "must (почти наверняка)"), p: [P("Dalilga asoslanib biror narsa rost ekaniga ishonchingiz komil bo'lsa, must + asosiy shakl ishlatiladi.", "must + начальная форма — когда вы уверены, что это правда, на основе фактов.")] },
      { h: P("can't (imkonsiz)", "can't (невозможно)"), p: [P("Biror narsa rost emasligiga ishonchingiz komil bo'lsa, can't ishlatiladi ('mustn't' emas).", "can't (а не «mustn't») — когда вы уверены, что это неправда.")] },
      { h: P("might / may / could (mumkin)", "might / may / could (возможно)"), p: [P("Mumkin, lekin aniq bo'lmagan narsalar uchun ishlatiladi.", "Для возможных, но неопределённых вещей.")] },
      { h: P("Continuous bilan", "С continuous"), p: [P("Hozir sodir bo'layotgan harakat uchun modal + be + -ing ishlatiladi.", "Для действия, происходящего сейчас: модальный глагол + be + -ing.")] },
    ],
    quiz: [
      P("Rostligiga ishonch → must be.", "Уверенность, что так → must be."),
      P("Unday emasligiga ishonch → can't be.", "Уверенность, что не так → can't be."),
      P("Mumkin → might be.", "Возможно → might be."),
      P("Imkonsiz → can't be.", "Невозможно → can't be."),
      P("Ehtimoliy izoh → might be out.", "Возможное объяснение → might be out."),
      P("Dalil → must be cold.", "Признаки → must be cold."),
      P("Kuchli xulosa → must be.", "Сильный вывод → must be."),
      P("Ehtimoli katta izoh → must be sleeping.", "Вероятное объяснение → must be sleeping."),
      P("Noto'g'riligiga ishonch → can't be.", "Уверенность, что неверно → can't be."),
      P("'could' = mumkin.", "«could» = возможно."),
      P("Ehtimoliy izoh uchun 'must be at work' (mustn't — taqiq).", "Для вероятного вывода — «must be at work» (mustn't — запрет)."),
      P("'might be ill' (mumkin) + 'can't be at the gym' (imkonsiz — sumkasi shu yerda).", "«might be ill» (возможно) + «can't be at the gym» (невозможно — сумка здесь)."),
      P("Unday emasligiga ishonch → can't be.", "Уверенность, что не так → can't be."),
      P("Ikkalasi ham noaniq → might be / might be.", "Оба неопределённы → might be / might be."),
      P("Modal + be + -ing: must be working.", "Модальный + be + -ing: must be working."),
    ],
  },
  g6: {
    situation: null,
    tip: P("Faqat to'ldiruvchisi bor (o'timli) fe'llar passiv bo'la oladi. 'happen', 'arrive' va 'sleep' to'ldiruvchi olmaydi, shuning uchun passiv bo'lmaydi.", "В пассив можно поставить только переходные глаголы (с дополнением). У «happen», «arrive» и «sleep» нет дополнения, поэтому они не бывают в пассиве."),
    blocks: [
      { h: P("Shakl: be + sifatdosh", "Форма: be + причастие"), p: [P("be ning kerakli zamoni + fe'lning 3-shakli. Hozirgi: am/is/are + pp. O'tgan: was/were + pp.", "Нужное время be + причастие. Настоящее: am/is/are + pp. Прошедшее: was/were + pp.")] },
      { h: P("by + bajaruvchi", "by + агент"), p: [P("Harakatni kim yoki nima bajarganini aytish uchun by ishlatiladi, lekin faqat bu muhim bo'lganda.", "by показывает, кто или что совершает действие, но только когда это важно.")] },
      { h: P("Passiv qachon ishlatiladi", "Когда употребляется пассив"), p: [P("Bajaruvchi noma'lum, ravshan yoki muhim bo'lmaganda, hamda rasmiy/ilmiy matnlarda ishlatiladi.", "Когда деятель неизвестен, очевиден или неважен, а также в официальных/научных текстах.")] },
      { h: P("Boshqa zamonlar", "Другие времена"), p: [P("Present perfect: has/have been + pp. Kelasi: will be + pp. Modal: can/must be + pp.", "Present perfect: has/have been + pp. Будущее: will be + pp. Модальные: can/must be + pp.")] },
    ],
    quiz: [
      P("Hozirgi zamon passivi: is spoken.", "Пассив в настоящем: is spoken."),
      P("O'tgan zamon passivi: was broken.", "Пассив в прошедшем: was broken."),
      P("Ko'plik ega → are made.", "Подлежащее во мн. числе → are made."),
      P("O'tgan zamon passivi: was written.", "Пассив в прошедшем: was written."),
      P("Ko'plik, hozirgi passiv: are cleaned.", "Мн. число, настоящий пассив: are cleaned."),
      P("O'tgan zamon passivi: was stolen.", "Пассив в прошедшем: was stolen."),
      P("Bajaruvchi → by.", "Агент → by."),
      P("has/have been + pp: has been done.", "has/have been + pp: has been done."),
      P("'arrive' to'ldiruvchi olmaydi → passiv bo'lmaydi.", "У «arrive» нет дополнения → не бывает в пассиве."),
      P("will be + pp: will be finished.", "will be + pp: will be finished."),
      P("Sifatdosh kerak: was written.", "Нужно причастие: was written."),
      P("Present perfect passivi: has been cleaned.", "Пассив в present perfect: has been cleaned."),
      P("was + sifatdosh: was caught.", "was + причастие: was caught."),
      P("Modal + be + pp: must be completed.", "Модальный + be + pp: must be completed."),
      P("Present continuous passivi: is being built.", "Пассив в present continuous: is being built."),
    ],
  },
  g7: {
    situation: null,
    tip: P("'tell' dan keyin tinglovchini aytish shart (tell me/him/us); 'say' dan keyin esa shart emas. 'He said me' — xato → 'He told me' yoki 'He said'.", "После «tell» обязательно называем слушателя (tell me/him/us); после «say» — нет. «He said me» — ошибка → «He told me» или «He said»."),
    blocks: [
      { h: P("Zamonni bir qadam orqaga surish", "Сдвиг времени назад"), p: [P("Zamon bir qadam orqaga suriladi: present simple → past simple; present continuous → past continuous; will → would; can → could.", "Время сдвигается на шаг назад: present simple → past simple; present continuous → past continuous; will → would; can → could.")] },
      { h: P("say va tell", "say и tell"), p: [P("tell + shaxs bilan; say esa shaxssiz (yoki 'to' bilan) ishlatiladi.", "tell — с указанием лица; say — без лица (или с «to»).")] },
      { h: P("Olmoshlar va vaqt so'zlari", "Местоимения и слова времени"), p: [P("Olmoshlar yangi so'zlovchiga moslanadi; today→that day, tomorrow→the next day, now→then kabi so'zlar o'zgaradi.", "Местоимения меняются под нового говорящего; today→that day, tomorrow→the next day, now→then.")] },
      { h: P("that (ixtiyoriy)", "that (необязательно)"), p: [P("say/tell dan keyin that ni qo'shish ham, tushirib qoldirish ham mumkin.", "После say/tell «that» можно ставить или опускать.")] },
    ],
    quiz: [
      P("Hozirgi → o'tgan: was.", "Настоящее → прошедшее: was."),
      P("will → would.", "will → would."),
      P("Hozirgi → o'tgan: lived.", "Настоящее → прошедшее: lived."),
      P("+ shaxs → told me.", "+ лицо → told me."),
      P("can → could.", "can → could."),
      P("Present continuous → past continuous: were eating.", "Present continuous → past continuous: were eating."),
      P("O'tgan → past perfect: had bought.", "Прошедшее → past perfect: had bought."),
      P("Shaxs yo'q → said.", "Без лица → said."),
      P("tomorrow → the next day.", "tomorrow → the next day."),
      P("Hozirgi → o'tgan: didn't like.", "Настоящее → прошедшее: didn't like."),
      P("'said' dan keyin shaxs bo'lmaydi; 'told me' ishlatiladi.", "После «said» нет лица; нужно «told me»."),
      P("Present perfect → past perfect: had finished.", "Present perfect → past perfect: had finished."),
      P("tell + shaxs: told me.", "tell + лицо: told me."),
      P("Present continuous → past continuous; now → then.", "Present continuous → past continuous; now → then."),
      P("can't → couldn't; tomorrow → the next day.", "can't → couldn't; tomorrow → the next day."),
    ],
  },
  g8: {
    situation: null,
    tip: P("Ko'chirilgan savollarda savol tartibi va 'do/did' saqlanmaydi: 'She asked where did I live' — xato → 'She asked where I lived.'", "В косвенных вопросах не сохраняются вопросительный порядок слов и «do/did»: «She asked where did I live» — ошибка → «She asked where I lived»."),
    blocks: [
      { h: P("Wh- savollar", "Wh-вопросы"), p: [P("Savol so'zi saqlanadi, keyin darak gap tartibi (ega + fe'l) keladi, do/does/did ishlatilmaydi.", "Сохраняется вопросительное слово, затем прямой порядок слов (подлежащее + глагол), без do/does/did.")] },
      { h: P("Ha/Yo'q savollar", "Вопросы да/нет"), p: [P("if yoki whether ishlatiladi, keyin darak gap tartibi.", "Используются if или whether, затем прямой порядок слов.")] },
      { h: P("Buyruq va iltimoslar", "Приказы и просьбы"), p: [P("told/asked + shaxs + to + fe'l ishlatiladi. Inkorda not to.", "told/asked + лицо + to + глагол. В отрицании — not to.")] },
      { h: P("So'roq belgisi yo'q", "Без вопросительного знака"), p: [P("Ko'chirilgan savollar darak gap, shuning uchun so'roq belgisi bilan tugamaydi.", "Косвенные вопросы — это утверждения, поэтому не оканчиваются вопросительным знаком.")] },
    ],
    quiz: [
      P("Darak tartibi, zamon orqaga: where I lived.", "Прямой порядок, сдвиг времени: where I lived."),
      P("Ha/Yo'q → if.", "Да/нет → if."),
      P("Buyruq → to sit.", "Приказ → to sit."),
      P("Inkor buyruq → not to run.", "Отрицательный приказ → not to run."),
      P("Zamon orqaga: what my name was.", "Сдвиг времени: what my name was."),
      P("if + darak tartibi, zamon orqaga: liked.", "if + прямой порядок, сдвиг: liked."),
      P("Iltimos → to open.", "Просьба → to open."),
      P("Present continuous → past continuous: was going.", "Present continuous → past continuous: was going."),
      P("can → could.", "can → could."),
      P("Darak tartibi: where I lived.", "Прямой порядок: where I lived."),
      P("Darak tartibi: what time it was.", "Прямой порядок: what time it was."),
      P("Inkor iltimos → asked me not to tell.", "Отрицательная просьба → asked me not to tell."),
      P("Ha/Yo'q + present perfect → if I had finished.", "Да/нет + present perfect → if I had finished."),
      P("Darak tartibi, zamon orqaga: why I was late.", "Прямой порядок, сдвиг: why I was late."),
      P("Buyruq → to wait; here → there.", "Приказ → to wait; here → there."),
    ],
  },
};
