// Full B2 grammar translations (g1–g8) — situation, tip, blocks, quiz explanations.
const P = (uz, ru) => ({ uz, ru });
export const B2_TR_1 = {
  g1: {
    situation: null,
    tip: P("If qismida hech qachon 'would have' ishlatmang: 'If I would have known' — xato → 'If I had known, I would have…'.", "Никогда не используйте 'would have' в if-части: 'If I would have known' — ошибка → 'If I had known, I would have…'."),
    blocks: [
      { h: P("Shakl: if + past perfect, would have + sifatdosh", "Форма: if + past perfect, would have + причастие"), p: [P("Ikkala qism ham endi o'zgartirib bo'lmaydigan, tasavvurdagi o'tmish haqida.", "Обе части описывают воображаемое прошлое, которое уже нельзя изменить.")] },
      { h: P("would / could / might have", "would / could / might have"), p: [P("'would have' o'rniga could have (imkoniyat/qobiliyat) yoki might have (ehtimoliy natija) ishlating.", "Вместо 'would have' используйте could have (возможность/способность) или might have (возможный результат).")] },
      { h: P("Qisqartmalar", "Сокращения"), p: [P("'I'd' — 'I had' yoki 'I would' bo'lishi mumkin. If qismida bu 'had', natija qismida — 'would'.", "'I'd' может означать 'I had' или 'I would'. В if-части это 'had', в части результата — 'would'.")] },
      { h: P("Qo'llanishi", "Употребление"), p: [P("Tugagan vaziyat haqida afsus, tanqid yoki yengil tortishni bildiradi.", "Выражает сожаление, критику или облегчение по поводу завершённой ситуации.")] },
    ],
    quiz: [
      P("Third conditional natijasi: would have passed.", "Результат third conditional: would have passed."),
      P("if + past perfect: had invited.", "if + past perfect: had invited."),
      P("Natija: would have arrived.", "Результат: would have arrived."),
      P("if + past perfect inkori: hadn't rained.", "if + past perfect, отрицание: hadn't rained."),
      P("Natija: would have won.", "Результат: would have won."),
      P("Natija: would have helped.", "Результат: would have helped."),
      P("O'tmishdagi imkoniyat → could have caught.", "Возможность в прошлом → could have caught."),
      P("if + past perfect: had tried.", "if + past perfect: had tried."),
      P("would have done.", "would have done."),
      P("O'tmishdagi noreal ehtimol → might have won.", "Нереальное прошлое → might have won."),
      P("If qismida 'would have' bo'lmaydi: had known.", "В if-части нет 'would have': had known."),
      P("had used + wouldn't have got.", "had used + wouldn't have got."),
      P("Third conditional = o'tmishdagi afsus.", "Third conditional = сожаление о прошлом."),
      P("would have caught + had left.", "would have caught + had left."),
      P("had asked + would have helped.", "had asked + would have helped."),
    ],
  },
  g2: {
    situation: null,
    tip: P("Har bir qismning vaqtini alohida aniqlang: sabab o'tmishda bo'lsa — past perfect; natija hozirda bo'lsa — 'would + asosiy shakl' ('would have' emas).", "Определяйте время каждой части отдельно: если причина в прошлом — past perfect; если результат в настоящем — 'would + начальная форма' (не 'would have')."),
    blocks: [
      { h: P("O'tmishdagi shart → hozirgi natija", "Прошлое условие → настоящий результат"), p: [P("if + past perfect, would + asosiy shakl. O'tmishdagi harakat hozirga ta'sir qiladi.", "if + past perfect, would + начальная форма. Действие в прошлом влияет на настоящее.")] },
      { h: P("Hozirgi shart → o'tmishdagi natija", "Настоящее условие → прошлый результат"), p: [P("if + past simple, would have + sifatdosh. Hozirgi (umumiy) fakt o'tmishga ta'sir qiladi.", "if + past simple, would have + причастие. Настоящий (общий) факт влияет на прошлое.")] },
      { h: P("Vaqt belgilari", "Маркеры времени"), p: [P("now, today, still kabi so'zlar ko'pincha o'tmishdagi sababdan kelib chiqqan hozirgi natijani ko'rsatadi.", "Слова now, today, still часто указывают на настоящий результат прошлой причины.")] },
      { h: P("Ma'nosi", "Значение"), p: [P("Mixed conditional'da ikkala qism ham noreal; faqat vaqt doiralari farq qiladi.", "В mixed conditional обе части нереальны; различаются только временные рамки.")] },
    ],
    quiz: [
      P("O'tmishdagi sabab → hozirgi natija: would live.", "Прошлая причина → настоящий результат: would live."),
      P("Hozirgi fakt → o'tmishdagi natija: would have come.", "Настоящий факт → прошлый результат: would have come."),
      P("O'tmishdagi sabab → hozirgi natija: would live.", "Прошлая причина → настоящий результат: would live."),
      P("Hozirgi xislat → o'tmishdagi natija: wouldn't have lost.", "Настоящая черта → прошлый результат: wouldn't have lost."),
      P("Hozirgi qobiliyat → o'tmishdagi natija: would have understood.", "Настоящая способность → прошлый результат: would have understood."),
      P("O'tmishdagi sabab → hozirgi natija: would be.", "Прошлая причина → настоящий результат: would be."),
      P("O'tmishdagi shart, hozirgi natija → mixed.", "Прошлое условие, настоящий результат → mixed."),
      P("Hozirgi fakt 'were' + o'tmishdagi natija 'would have helped'.", "Настоящий факт 'were' + прошлый результат 'would have helped'."),
      P("Hozirgi natija → would be ('would have been' emas).", "Настоящий результат → would be (не 'would have been')."),
      P("O'tmishdagi sabab 'had brought' + hozirgi natija 'wouldn't be'.", "Прошлая причина 'had brought' + настоящий результат 'wouldn't be'."),
      P("Hozirgi xislat 'were' + o'tmishdagi natija 'would have said'.", "Настоящая черта 'were' + прошлый результат 'would have said'."),
      P("Hozirgi xislat + o'tmishdagi natija.", "Настоящая черта + прошлый результат."),
      P("O'tmishdagi sabab 'had learnt' + hozirgi natija 'would have'.", "Прошлая причина 'had learnt' + настоящий результат 'would have'."),
      P("O'tmishdagi sabab → hozirgi natija.", "Прошлая причина → настоящий результат."),
      P("Hozirgi fakt → o'tmishdagi natija: would have gone.", "Настоящий факт → прошлый результат: would have gone."),
    ],
  },
  g3: {
    situation: null,
    tip: P("O'zingiz haqingizda 'wish + would' ishlatmang. 'I wish I could…' deng, 'I wish I would…' emas. 'would' — boshqa odamlarning xatti-harakati uchun.", "Не используйте 'wish + would' о себе. Говорите 'I wish I could…', а не 'I wish I would…'. 'would' — о поведении других людей."),
    blocks: [
      { h: P("wish + past simple (hozirgi)", "wish + past simple (настоящее)"), p: [P("Boshqacha bo'lishini istagan hozirgi vaziyatlar uchun past simple (yoki 'were') ishlatiladi.", "Для настоящих ситуаций, которые хотим изменить, используется past simple (или 'were').")] },
      { h: P("wish + past perfect (o'tmish)", "wish + past perfect (прошлое)"), p: [P("O'tmishdagi afsuslar uchun past perfect ishlatiladi.", "Для сожалений о прошлом используется past perfect.")] },
      { h: P("wish + would (norozilik)", "wish + would (раздражение)"), p: [P("Boshqa odamning bezovta qiluvchi odati yoki istalgan o'zgarish uchun would ishlatiladi.", "О раздражающем поведении другого человека или желаемом изменении — would.")] },
      { h: P("if only", "if only"), p: [P("if only xuddi 'wish' kabi ishlaydi, lekin kuchliroq his-tuyg'uni bildiradi.", "if only работает как 'wish', но звучит более эмоционально.")] },
    ],
    quiz: [
      P("Hozirgi istak → were.", "Желание о настоящем → were."),
      P("O'tmishdagi afsus → had studied.", "Сожаление о прошлом → had studied."),
      P("Bezovta qiluvchi odat → would stop.", "Раздражающее поведение → would stop."),
      P("Hozirgi istak → had.", "Желание о настоящем → had."),
      P("O'zgarishni istash → would stop.", "Желание изменения → would stop."),
      P("O'tmishdagi afsus → had known.", "Сожаление о прошлом → had known."),
      P("Hozirgi qobiliyat istagi → could.", "Желание способности сейчас → could."),
      P("Boshqalarning odati → wouldn't make.", "Поведение других → wouldn't make."),
      P("O'tmishdagi afsus → hadn't sent.", "Сожаление о прошлом → hadn't sent."),
      P("Hozirgi vaziyat → past simple: lived.", "Настоящая ситуация → past simple: lived."),
      P("O'zingiz haqingizda 'wish + would' ishlatilmaydi: I wish I were.", "О себе не говорят 'wish + would': I wish I were."),
      P("O'tmishdagi afsus 'had taken' + kelajakdagi o'zgarish istagi 'would give'.", "Сожаление 'had taken' + желание изменения 'would give'."),
      P("Past perfect → had met.", "Past perfect → had met."),
      P("Bezovta qiluvchi odat → would listen.", "Раздражающая привычка → would listen."),
      P("O'tmishdagi afsus → wish + past perfect.", "Сожаление о прошлом → wish + past perfect."),
    ],
  },
  g4: {
    situation: null,
    tip: P("'He is said to have left' gapida harakat xabardan oldin bo'lsa, perfect infinitive (to have + sifatdosh) ishlatiladi.", "В 'He is said to have left' используется perfect infinitive (to have + причастие), когда действие произошло раньше сообщения."),
    blocks: [
      { h: P("Barcha zamonlar", "Все времена"), p: [P("Passiv 'be' fe'lining kerakli zamoni + sifatdosh bilan yasaladi, jumladan perfect va continuous shakllari ham.", "Пассив образуется нужным временем глагола 'be' + причастие, включая perfect и continuous формы.")] },
      { h: P("It is said that…", "It is said that…"), p: [P("Umumiy fikrlarni bildirish uchun It + is/was + xabar fe'li + that… ishlatiladi.", "Для передачи общего мнения: It + is/was + глагол сообщения + that….")] },
      { h: P("Ega + is said to…", "Подлежащее + is said to…"), p: [P("Ikkinchi qolip: Ega + is/was + said/thought + to + infinitive.", "Второй шаблон: подлежащее + is/was + said/thought + to + инфинитив.")] },
      { h: P("have/get something done", "have/get something done"), p: [P("Kimdir siz uchun xizmat bajarganda have/get + obyekt + sifatdosh ishlatiladi (causative mavzusiga qarang).", "Когда кто-то делает услугу для вас: have/get + объект + причастие (см. каузатив).")] },
    ],
    quiz: [
      P("Present continuous passiv: is being repaired.", "Пассив present continuous: is being repaired."),
      P("Past perfect passiv: had been delivered.", "Пассив past perfect: had been delivered."),
      P("Shaxssiz xabar: It is said that.", "Безличное сообщение: It is said that."),
      P("Kelasi zamon passivi: will be sold.", "Пассив будущего времени: will be sold."),
      P("Continuous passiv: being discussed.", "Пассив continuous: being discussed."),
      P("It is believed that…", "It is believed that…"),
      P("Ega + is said + to be.", "Подлежащее + is said + to be."),
      P("Future perfect passiv: will have been finished.", "Пассив future perfect: will have been finished."),
      P("Oldinroq bo'lgan harakat → to have left.", "Более раннее действие → to have left."),
      P("She is said to be rich.", "She is said to be rich."),
      P("Sifatdosh kerak: has left.", "Нужно причастие: has left."),
      P("Present perfect passiv: has been implemented.", "Пассив present perfect: has been implemented."),
      P("to have + sifatdosh: to have stolen.", "to have + причастие: to have stolen."),
      P("Past continuous passiv: was being built.", "Пассив past continuous: was being built."),
      P("is believed to have lost money.", "is believed to have lost money."),
    ],
  },
  g5: {
    situation: null,
    tip: P("Fe'lni o'z qolipiga moslang: 'suggest' -ing yoki 'that…' oladi, hech qachon 'to' emas. 'He suggested to go' — xato → 'He suggested going'.", "Подбирайте глаголу его шаблон: 'suggest' требует -ing или 'that…', никогда 'to'. 'He suggested to go' — ошибка → 'He suggested going'."),
    blocks: [
      { h: P("fe'l + to-infinitive", "глагол + to-инфинитив"), p: [P("offer, promise, agree, refuse, threaten, decide.", "offer, promise, agree, refuse, threaten, decide.")] },
      { h: P("fe'l + obyekt + to-infinitive", "глагол + объект + to-инфинитив"), p: [P("advise, ask, tell, warn, remind, encourage, invite.", "advise, ask, tell, warn, remind, encourage, invite.")] },
      { h: P("fe'l + -ing", "глагол + -ing"), p: [P("suggest, admit, deny, recommend, mention.", "suggest, admit, deny, recommend, mention.")] },
      { h: P("fe'l + predlog + -ing", "глагол + предлог + -ing"), p: [P("apologise for, insist on, accuse sb of, congratulate sb on.", "apologise for, insist on, accuse sb of, congratulate sb on.")] },
    ],
    quiz: [
      P("offer + to: to help.", "offer + to: to help."),
      P("suggest + -ing: taking.", "suggest + -ing: taking."),
      P("advise + obyekt + to: to see.", "advise + объект + to: to see."),
      P("admit + -ing: breaking.", "admit + -ing: breaking."),
      P("refuse + to: to answer.", "refuse + to: to answer."),
      P("apologise for + -ing: for being.", "apologise for + -ing: for being."),
      P("warn + obyekt + not to: not to stay.", "warn + объект + not to: not to stay."),
      P("insist on + -ing: on paying.", "insist on + -ing: on paying."),
      P("deny + -ing: doing.", "deny + -ing: doing."),
      P("invite + obyekt + to: to join.", "invite + объект + to: to join."),
      P("suggest + -ing: suggested meeting.", "suggest + -ing: suggested meeting."),
      P("promise + to: promised to pay back.", "promise + to: promised to pay back."),
      P("admit + -ing: admitted taking it.", "admit + -ing: admitted taking it."),
      P("advise + obyekt + to: advised him to rest.", "advise + объект + to: advised him to rest."),
      P("congratulate sb on + -ing.", "congratulate sb on + -ing."),
    ],
  },
  g6: {
    situation: null,
    tip: P("Xulosa chiqarishda 'must have'ning aksi — 'can't have', 'mustn't have' emas. Standart ingliz tilida xulosa uchun 'mustn't have' ishlatilmaydi.", "Противоположность 'must have' при умозаключении — 'can't have', а не 'mustn't have'. 'Mustn't have' в этом значении не используется."),
    blocks: [
      { h: P("must have (deyarli aniq)", "must have (почти уверенность)"), p: [P("Biror narsa bo'lganiga ishonchingiz komil bo'lsa, must have + sifatdosh ishlating.", "Когда вы уверены, что что-то произошло: must have + причастие.")] },
      { h: P("can't / couldn't have (imkonsiz)", "can't / couldn't have (невозможно)"), p: [P("Bo'lmaganiga ishonchingiz komil bo'lsa, can't/couldn't have + sifatdosh ishlating.", "Когда вы уверены, что этого не было: can't/couldn't have + причастие.")] },
      { h: P("might / may / could have (ehtimol)", "might / may / could have (возможно)"), p: [P("Ehtimol bo'lgan, lekin aniq bilmagan narsalar uchun shularni ishlating.", "Для того, что возможно произошло, но вы не уверены.")] },
      { h: P("should have (tanqid/afsus)", "should have (критика/сожаление)"), p: [P("Bo'lishi kerak bo'lgan, lekin bo'lmagan to'g'ri ish uchun should have + sifatdosh (afsus yoki tanqid).", "Для правильного действия, которое не произошло: should have + причастие (сожаление или критика).")] },
    ],
    quiz: [
      P("Bo'lganiga ishonch → must have rained.", "Уверенность, что произошло → must have rained."),
      P("Ishonch → must have heard.", "Уверенность → must have heard."),
      P("Bo'lmaganiga ishonch → can't have seen.", "Уверенность, что не было → can't have seen."),
      P("Ehtimol → might have gone.", "Возможно → might have gone."),
      P("Tanqid/afsus → should have told.", "Критика/сожаление → should have told."),
      P("Ishonch → must have eaten.", "Уверенность → must have eaten."),
      P("Bo'lmaganiga ishonch → can't have studied.", "Уверенность, что не было → can't have studied."),
      P("Ehtimol → might have been.", "Возможно → might have been."),
      P("Afsus → shouldn't have eaten.", "Сожаление → shouldn't have eaten."),
      P("can't have = bo'lmaganiga ishonch.", "can't have = уверенность, что не произошло."),
      P("Inkor xulosa uchun 'can't have' ishlatiladi.", "Для отрицательного вывода — 'can't have'."),
      P("must have broken in (ishonch) + might have forgotten (ehtimol).", "must have broken in (уверенность) + might have forgotten (возможно)."),
      P("should have = afsus.", "should have = сожаление."),
      P("Qiyin bo'lmaganiga ishonch → can't have been.", "Уверенность, что не был сложным → can't have been."),
      P("should have + sifatdosh: should have called.", "should have + причастие: should have called."),
    ],
  },
  g7: {
    situation: null,
    tip: P("Predlogdan keyin whom ('who' emas) va which ('that' emas) ishlatiladi: 'the person to whom…', 'the tool with which…'. 'To that' va 'to who' bu yerda xato.", "После предлога используйте whom (не 'who') и which (не 'that'): 'the person to whom…', 'the tool with which…'. 'To that' и 'to who' здесь ошибочны."),
    blocks: [
      { h: P("Predlog + which/whom", "Предлог + which/whom"), p: [P("Rasmiy ingliz tilida predlog nisbiy olmoshdan (which/whom) oldin kelishi mumkin.", "В формальном английском предлог может стоять перед относительным местоимением (which/whom).")] },
      { h: P("Norasmiy: predlog oxirida", "Неформально: предлог в конце"), p: [P("Kundalik nutqda predlog odatda gap oxiriga ko'chadi, olmosh esa tushib qolishi mumkin.", "В повседневной речи предлог обычно уходит в конец, а местоимение может опускаться.")] },
      { h: P("miqdor so'zi + of whom/which", "квантификатор + of whom/which"), p: [P("Ajratuvchi bo'lmagan gaplarda all/some/many/none/both + of whom/which ishlatiladi.", "В неограничительных придаточных: all/some/many/none/both + of whom/which.")] },
      { h: P("whose", "whose"), p: [P("whose odamlar va narsalar uchun egalikni bildiradi.", "whose выражает принадлежность для людей и предметов.")] },
    ],
    quiz: [
      P("Predlog + whom: to whom.", "Предлог + whom: to whom."),
      P("born in a house → in which.", "born in a house → in which."),
      P("Egalik → whose.", "Принадлежность → whose."),
      P("speak to → predlog oxirida: to.", "speak to → предлог в конце: to."),
      P("both of whom.", "both of whom."),
      P("cut with → with which.", "cut with → with which."),
      P("some of whom.", "some of whom."),
      P("Egalik (kompaniyaniki) → whose.", "Принадлежность (компании) → whose."),
      P("decide on → on which.", "decide on → on which."),
      P("with whom I work.", "with whom I work."),
      P("Predlogdan keyin 'whom', 'that' emas.", "После предлога — 'whom', а не 'that'."),
      P("Narsalar → all of which.", "Предметы → all of which."),
      P("based on → on which.", "based on → on which."),
      P("Odamlar → none of whom.", "Люди → none of whom."),
      P("Egalik → whose paintings.", "Принадлежность → whose paintings."),
    ],
  },
  g8: {
    situation: null,
    tip: P("Tartib: have + OBYEKT + sifatdosh, 'have + sifatdosh + obyekt' emas. 'I had my car washed' deng, 'I had washed my car' emas (bu o'zingiz yuvganingizni bildiradi).", "Порядок: have + ОБЪЕКТ + причастие, а не 'have + причастие + объект'. Говорите 'I had my car washed', а не 'I had washed my car' (это значит, что вы сделали это сами)."),
    blocks: [
      { h: P("have + obyekt + sifatdosh", "have + объект + причастие"), p: [P("Standart qolip: have + narsa + sifatdosh.", "Стандартная структура: have + предмет + причастие.")] },
      { h: P("get + obyekt + sifatdosh", "get + объект + причастие"), p: [P("get — 'have'ning norasmiyroq muqobili.", "get — более разговорная альтернатива 'have'.")] },
      { h: P("Barcha zamonlar", "Все времена"), p: [P("'have/get' fe'lining zamonini kerak bo'lganda o'zgartiring.", "Меняйте время глагола 'have/get' по необходимости.")] },
      { h: P("Yoqimsiz hodisalar", "Неприятные события"), p: [P("Xuddi shu qolip boshingizga tushgan yomon hodisani ham tasvirlashi mumkin.", "Та же структура может описывать неприятность, случившуюся с вами.")] },
    ],
    quiz: [
      P("Causative o'tgan zamon: had my hair cut.", "Каузатив в прошедшем: had my hair cut."),
      P("have the house painted.", "have the house painted."),
      P("got her car repaired.", "got her car repaired."),
      P("have + obyekt + sifatdosh.", "have + объект + причастие."),
      P("Sifatdosh: tested.", "Причастие: tested."),
      P("Present continuous: having.", "Present continuous: having."),
      P("Odat, present simple: get.", "Привычка, present simple: get."),
      P("had her bag stolen.", "had her bag stolen."),
      P("Present perfect: 'have just had' shaklini 'had' to'ldiradi.", "Present perfect: 'had' завершает форму 'have just had'."),
      P("Causative: had the door painted.", "Каузатив: had the door painted."),
      P("Causative uchun obyekt + sifatdosh kerak: had my bike repaired.", "Каузативу нужен объект + причастие: had my bike repaired."),
      P("get + obyekt + sifatdosh: get it looked at.", "get + объект + причастие: get it looked at."),
      P("had his car stolen = yomon hodisa.", "had his car stolen = неприятное событие."),
      P("had + obyekt + sifatdosh: had it cancelled.", "had + объект + причастие: had it cancelled."),
      P("have + obyekt + sifatdosh: have the roof fixed.", "have + объект + причастие: have the roof fixed."),
    ],
  },
};
