// Full B2 grammar translations (g9–g15) — situation, tip, blocks, quiz explanations.
const P = (uz, ru) => ({ uz, ru });
export const B2_TR_2 = {
  g9: {
    situation: null,
    tip: P("'remember/forget' bilan: bajarilishi kerak bo'lgan vazifa uchun infinitive, allaqachon bo'lib o'tgan narsaning xotirasi uchun -ing shakli ishlatiladi.", "С 'remember/forget': инфинитив — для задачи, которую нужно сделать, форма -ing — для воспоминания об уже сделанном."),
    blocks: [
      { h: P("remember / forget", "remember / forget"), p: [P("+ to = vazifa keyin bajariladi; + -ing = xotira oldin bo'lgan voqea haqida.", "+ to = обязанность идёт после; + -ing = воспоминание о том, что было раньше.")] },
      { h: P("stop", "stop"), p: [P("stop + -ing = harakatni tugatish; stop + to = biror narsa qilish uchun to'xtash.", "stop + -ing = прекратить действие; stop + to = остановиться, чтобы что-то сделать.")] },
      { h: P("try", "try"), p: [P("try + -ing = sinab ko'rish (tajriba); try + to = qiyin narsaga urinish.", "try + -ing = поэкспериментировать; try + to = попытаться сделать трудное.")] },
      { h: P("regret / mean / go on", "regret / mean / go on"), p: [P("regret + -ing = o'tmishdan afsuslanish; regret + to = aytishdan afsusda bo'lish. mean + -ing = talab qilmoq; mean + to = niyat qilmoq.", "regret + -ing = сожалеть о прошлом; regret + to = с сожалением сообщать. mean + -ing = подразумевать/требовать; mean + to = намереваться.")] },
    ],
    quiz: [
      P("Bajarilishi kerak bo'lgan vazifa → to lock.", "Задача, которую нужно сделать → to lock."),
      P("Xotira → meeting.", "Воспоминание → meeting."),
      P("Harakatni tugatdi → stopped smoking.", "Прекратил действие → stopped smoking."),
      P("Maqsad uchun to'xtadi → to take.", "Остановились, чтобы → to take."),
      P("Aytishdan afsusda → regret to say.", "С сожалением сообщать → regret to say."),
      P("Sinab ko'rish → try adding.", "Эксперимент → try adding."),
      P("Qiyin narsaga urinish → tried to open.", "Попытка трудного → tried to open."),
      P("mean = talab qilmoq → moving.", "mean = подразумевать → moving."),
      P("mean = niyat qilmoq → to call.", "mean = намереваться → to call."),
      P("Vazifa → to take.", "Обязанность → to take."),
      P("O'tmishdan afsus → regret telling.", "Сожаление о прошлом → regret telling."),
      P("Xotira 'seeing' + vazifa 'to buy'.", "Воспоминание 'seeing' + задача 'to buy'."),
      P("stop + to = maqsad uchun to'xtash.", "stop + to = остановиться, чтобы сделать."),
      P("regret to inform + passiv + tried to find.", "regret to inform + пассив + tried to find."),
      P("to-infinitive = vazifa; stop + -ing = tashlash.", "to-инфинитив = задача; stop + -ing = бросить."),
    ],
  },
  g10: {
    situation: null,
    tip: P("Kelajakdagi aniq paytda davom etadigan harakat uchun future continuous, o'sha paytgacha tugaydigan harakat uchun future perfect ishlatiladi.", "Future continuous — для действия в процессе в будущий момент, future perfect — для действия, завершённого до этого момента."),
    blocks: [
      { h: P("Future continuous: will be + -ing", "Future continuous: will be + -ing"), p: [P("Kelajakdagi aniq vaqtda davom etib turadigan harakat.", "Действие, которое будет в процессе в конкретный момент будущего.")] },
      { h: P("Future perfect: will have + sifatdosh", "Future perfect: will have + причастие"), p: [P("Kelajakdagi vaqtdan oldin tugaydigan harakat, ko'pincha 'by' bilan.", "Действие, которое завершится до будущего момента, часто с 'by'.")] },
      { h: P("by / by the time", "by / by the time"), p: [P("Future perfect bilan by + vaqt yoki by the time + gap ishlatiladi.", "С future perfect используйте by + время или by the time + придаточное.")] },
      { h: P("Future perfect continuous", "Future perfect continuous"), p: [P("will have been + -ing kelajakdagi nuqtagacha bo'lgan davomiylikni ta'kidlaydi.", "will have been + -ing подчёркивает длительность до будущего момента.")] },
    ],
    quiz: [
      P("Kelajakda davomida → will be flying.", "В процессе в будущем → will be flying."),
      P("Kelajakdagi vaqtdan oldin tugaydi → will have built.", "Завершено до будущего момента → will have built."),
      P("Davomida → will be watching.", "В процессе → will be watching."),
      P("Oldin tugagan bo'ladi → will have left.", "Завершится раньше → will have left."),
      P("Davomida → will be driving.", "В процессе → will be driving."),
      P("Muddatgacha tugaydi → will have finished.", "Завершено к сроку → will have finished."),
      P("Davomida → will be relaxing.", "В процессе → will be relaxing."),
      P("Kelajakdagi nuqtagacha davomiylik → will have been working.", "Длительность до будущей точки → will have been working."),
      P("Oldin tugagan bo'ladi → will have found.", "Завершено раньше → will have found."),
      P("will be eating = davomida.", "will be eating = в процессе."),
      P("Kelajakdagi vaqtdan oldin tugaydi → will have finished.", "Завершено до будущего момента → will have finished."),
      P("Davomida 'will be taking' + tugagan 'will have finished'.", "В процессе 'will be taking' + завершено 'will have finished'."),
      P("will have been writing = davomiylik.", "will have been writing = длительность."),
      P("Nuqtagacha davomiylik → will have been sitting.", "Длительность до момента → will have been sitting."),
      P("will have + sifatdosh: will have left.", "will have + причастие: will have left."),
    ],
  },
  g11: {
    situation: null,
    tip: P("Holat fe'llari bilan continuous ishlatmang. 'I had known her for years' deng, 'I had been knowing' emas.", "Не используйте continuous с глаголами состояния. Говорите 'I had known her for years', а не 'I had been knowing'."),
    blocks: [
      { h: P("Shakl: had been + -ing", "Форма: had been + -ing"), p: [P("O'tmishdagi nuqtagacha davom etgan harakat uchun had been + fe'l-ing ishlatiladi.", "had been + глагол-ing — для действия, длившегося до момента в прошлом.")] },
      { h: P("O'tmishdagi natijani izohlash", "Объяснение прошлого результата"), p: [P("Ko'pincha o'tmishdagi paytda nima uchun shunday bo'lganini izohlaydi.", "Часто объясняет, почему в прошлый момент дело обстояло так.")] },
      { h: P("for / since bilan", "с for / since"), p: [P("for + davr va since + boshlanish nuqtasi ishlatiladi.", "for + период и since + точка отсчёта.")] },
      { h: P("past perfect simple bilan taqqoslash", "сравнение с past perfect simple"), p: [P("Continuous harakat/davomiylikni, simple esa tugallangan natijani ta'kidlaydi.", "Continuous подчёркивает процесс/длительность, simple — завершённый результат.")] },
    ],
    quiz: [
      P("O'tmishdagi nuqtagacha davomiylik → had been waiting.", "Длительность до момента в прошлом → had been waiting."),
      P("O'tmishdagi natijani izohlaydi → had been crying.", "Объясняет прошлый результат → had been crying."),
      P("Davomiylik → had been driving.", "Длительность → had been driving."),
      P("had been + -ing.", "had been + -ing."),
      P("Oldinroq bo'lgan harakat → had been raining.", "Более раннее действие → had been raining."),
      P("O'tmishdagi voqeadan oldingi davomiylik → had been waiting.", "Длительность до прошлого события → had been waiting."),
      P("Holatni izohlaydi → had been running.", "Объясняет состояние → had been running."),
      P("Davomiylik → had they been dating.", "Длительность → had they been dating."),
      P("'know' — holat fe'li.", "'know' — глагол состояния."),
      P("Davomiylik → had been reading.", "Длительность → had been reading."),
      P("Holat fe'li: had known.", "Глагол состояния: had known."),
      P("O'tmishdagi nuqtagacha davomiylik → had been swimming.", "Длительность до момента в прошлом → had been swimming."),
      P("Tugallangan → past perfect simple: had painted.", "Завершено → past perfect simple: had painted."),
      P("Natijani izohlagan davomiy harakat → had been playing.", "Длительное действие, объясняющее результат → had been playing."),
      P("had been + -ing: had been living.", "had been + -ing: had been living."),
    ],
  },
  g12: {
    situation: null,
    tip: P("Inversion'da savoldagi kabi yordamchi fe'l ishlatiladi: 'Never have I…', 'Rarely does he…', 'Not only did she…'. Bu so'zlardan keyin oddiy so'z tartibini ishlatmang.", "В инверсии используется тот же вспомогательный глагол, что в вопросе: 'Never have I…', 'Rarely does he…', 'Not only did she…'. После таких слов обычный порядок слов не подходит."),
    blocks: [
      { h: P("Inkor ravishlari", "Отрицательные наречия"), p: [P("Gap boshidagi never, rarely, seldom, hardly, no sooner, not only, little so'zlaridan keyin ega va yordamchi fe'l o'rin almashadi.", "После never, rarely, seldom, hardly, no sooner, not only, little в начале предложения подлежащее и вспомогательный глагол меняются местами.")] },
      { h: P("hardly… when / no sooner… than", "hardly… when / no sooner… than"), p: [P("Bir voqea ketidan tez keladigan ikkinchi voqea uchun ishlatiladi.", "Для одного события, быстро следующего за другим.")] },
      { h: P("not only… but also", "not only… but also"), p: [P("Not only + yordamchi fe'l + ega, … but also …", "Not only + вспомогательный глагол + подлежащее, … but also …")] },
      { h: P("only + vaqt iborasi", "only + выражение времени"), p: [P("only then / only after / only when / not until dan keyin inversion qilinadi.", "После only then / only after / only when / not until — инверсия.")] },
    ],
    quiz: [
      P("Inversion: have I seen.", "Инверсия: have I seen."),
      P("Inversion: does she go.", "Инверсия: does she go."),
      P("Inversion: was he.", "Инверсия: was he."),
      P("Inversion: do we see.", "Инверсия: do we see."),
      P("Inversion: had I sat.", "Инверсия: had I sat."),
      P("No sooner … than.", "No sooner … than."),
      P("Inversion: did he know.", "Инверсия: did he know."),
      P("Inversion: did I feel.", "Инверсия: did I feel."),
      P("Inversion: did they hear.", "Инверсия: did they hear."),
      P("Hardly … when.", "Hardly … when."),
      P("Inversion: Never have I eaten.", "Инверсия: Never have I eaten."),
      P("No sooner had he opened … than.", "No sooner had he opened … than."),
      P("Not only does she sing, but she also dances.", "Not only does she sing, but she also dances."),
      P("'Only after'dan keyin inversion: did I realise.", "Инверсия после 'Only after': did I realise."),
      P("Rarely had I felt so happy.", "Rarely had I felt so happy."),
    ],
  },
  g13: {
    situation: null,
    tip: P("What-cleft'da 'what' ega bo'lsa, 'be' fe'li ko'plik g'oyasidan oldin ham birlikda bo'ladi: 'What I need is answers' ('are' emas).", "В What-cleft глагол 'be' стоит в единственном числе, даже перед множественной идеей, если 'what' — подлежащее: 'What I need is answers' (не 'are')."),
    blocks: [
      { h: P("It-cleft: It + be + urg'u + that/who…", "It-cleft: It + be + фокус + that/who…"), p: [P("Shaxs, narsa, vaqt yoki joyni ta'kidlash uchun.", "Для выделения человека, предмета, времени или места.")] },
      { h: P("What-cleft: What… + be + urg'u", "What-cleft: What… + be + фокус"), p: [P("Butun g'oyani, ko'pincha harakat yoki ehtiyojni ta'kidlaydi.", "Выделяет целую идею, часто действие или потребность.")] },
      { h: P("The thing / the reason / the place", "The thing / the reason / the place"), p: [P("Boshqa boshlovchi so'zlar ham urg'u qo'shadi.", "Другие вводные конструкции тоже добавляют фокус.")] },
      { h: P("All (that)…", "All (that)…"), p: [P("All 'yagona narsa' ma'nosini berishi mumkin.", "All может означать 'единственное, что'.")] },
    ],
    quiz: [
      P("It-cleft: It was Tom who…", "It-cleft: It was Tom who…"),
      P("What-cleft, birlik: is.", "What-cleft, единственное число: is."),
      P("Joy/vaqt it-cleft: that.", "It-cleft места/времени: that."),
      P("All = yagona narsa.", "All = единственное, что."),
      P("Shaxs → who.", "Человек → who."),
      P("What-cleft: was (to) apologise.", "What-cleft: was (to) apologise."),
      P("The reason why.", "The reason why."),
      P("It-cleft: that matters.", "It-cleft: that matters."),
      P("'What' birlikda → was.", "'What' в единственном числе → was."),
      P("The place where… = joyga urg'u.", "The place where… = фокус на месте."),
      P("Ega bo'lgan 'what' → birlik: is.", "'What' как подлежащее → единственное число: is."),
      P("It was John who sent the email.", "It was John who sent the email."),
      P("What we should do is tell the truth.", "What we should do is tell the truth."),
      P("The reason why he left was the noise.", "The reason why he left was the noise."),
      P("The thing that I admire is her honesty.", "The thing that I admire is her honesty."),
    ],
  },
  g14: {
    situation: null,
    tip: P("Gapdan oldin 'although', ot yoki -ing dan oldin 'despite / in spite of' ishlatiladi. 'Despite it was raining' — xato → 'Despite the rain' yoki 'Although it was raining'.", "Перед придаточным — 'although', перед существительным или -ing — 'despite / in spite of'. 'Despite it was raining' — ошибка → 'Despite the rain' или 'Although it was raining'."),
    blocks: [
      { h: P("although / even though / though + gap", "although / even though / though + придаточное"), p: [P("Keyin ega + fe'l keladi.", "После них идёт подлежащее + глагол.")] },
      { h: P("despite / in spite of + ot/-ing", "despite / in spite of + существительное/-ing"), p: [P("Keyin ot yoki -ing shakli keladi, gap emas. Gap ishlatish uchun 'the fact that' qo'shing.", "После них — существительное или -ing, а не придаточное. Для придаточного добавьте 'the fact that'.")] },
      { h: P("however / nevertheless (ravishlar)", "however / nevertheless (наречия)"), p: [P("Ikkita gapni bog'laydi; odatda yangi gapni boshlab, keyin vergul qo'yiladi.", "Связывают два предложения; обычно начинают новое предложение, после — запятая.")] },
      { h: P("whereas / while (ikki faktni qarshilantirish)", "whereas / while (противопоставление фактов)"), p: [P("Ikki g'oya o'rtasidagi to'g'ridan-to'g'ri qarama-qarshilikni ko'rsatadi.", "Показывают прямой контраст между двумя идеями.")] },
    ],
    quiz: [
      P("+ gap → Although.", "+ придаточное → Although."),
      P("+ ot → Despite.", "+ существительное → Despite."),
      P("Ikki faktni qarshilantirish → whereas.", "Контраст двух фактов → whereas."),
      P("Ikki gapni bog'laydi → However.", "Связывает два предложения → However."),
      P("in spite of + ot.", "in spite of + существительное."),
      P("+ -ing → Despite being tired.", "+ -ing → Despite being tired."),
      P("+ gap → Even though.", "+ придаточное → Even though."),
      P("Although + gap.", "Although + придаточное."),
      P("Gaplarni bog'lovchi ravish → Nevertheless.", "Наречие, связывающее предложения → Nevertheless."),
      P("despite the fact that + gap.", "despite the fact that + придаточное."),
      P("Despite + ot/-ing; gapdan oldin 'Although'.", "Despite + существительное/-ing; перед придаточным — 'Although'."),
      P("Despite + ot 'his wealth' + whereas (qarshilantirish).", "Despite + существительное 'his wealth' + whereas (контраст)."),
      P("in spite of + ot.", "in spite of + существительное."),
      P("Despite + -ing 'being cheaper' + whereas (qarshilantirish).", "Despite + -ing 'being cheaper' + whereas (контраст)."),
      P("However ikkita alohida gapni bog'laydi.", "However связывает два отдельных предложения."),
    ],
  },
  g15: {
    situation: null,
    tip: P("Ot kontekst orqali aniq bo'lsa 'the' ishlatiladi ('the book you lent me'), ko'plik/sanoqsiz otlar bilan umumiy gaplarda esa artikl ishlatilmaydi ('books are useful').", "Используйте 'the', когда существительное конкретизировано контекстом ('the book you lent me'), и нулевой артикль в общих утверждениях с множественными/неисчисляемыми ('books are useful')."),
    blocks: [
      { h: P("the — yagona / aniqlangan narsa uchun", "the — для уникального / конкретного"), p: [P("Kontekst otni aniq qilganda, superlativlardan keyin va 'the only/same/first' bilan the ishlatiladi.", "the — когда контекст делает существительное конкретным, после превосходной степени и с 'the only/same/first'.")] },
      { h: P("Umumiy ma'noda artiklsiz", "Нулевой артикль в общем значении"), p: [P("Umumiy ma'nodagi ko'plik va sanoqsiz otlar bilan artikl ishlatilmaydi.", "Без артикля — множественные и неисчисляемые существительные в общем смысле.")] },
      { h: P("the + sifat (guruhlar)", "the + прилагательное (группы)"), p: [P("the + sifat butun bir guruh odamlarni bildirishi mumkin.", "the + прилагательное может обозначать целую группу людей.")] },
      { h: P("Aniqlovchilar va 'of'", "Определители и 'of'"), p: [P("the/my/these bilan of ishlatiladi: 'most of the students', 'none of my friends'; umumiy ma'noda 'of'siz: 'most students'.", "of — с the/my/these: 'most of the students', 'none of my friends'; в общем смысле без 'of': 'most students'.")] },
    ],
    quiz: [
      P("Kontekst orqali aniqlangan → The book you recommended.", "Конкретизировано контекстом → The book you recommended."),
      P("Umumiy sanoqsiz ot → artiklsiz.", "Общее неисчисляемое → без артикля."),
      P("the + sifat = guruh: the poor.", "the + прилагательное = группа: the poor."),
      P("+ the → Most of the students.", "+ the → Most of the students."),
      P("'only' → the only person.", "'only' → the only person."),
      P("Umumiy ko'plik → artiklsiz: dogs.", "Общее множественное → без артикля: dogs."),
      P("'in this bottle' bilan aniqlangan → The water.", "Конкретизировано 'in this bottle' → The water."),
      P("Umumiy ko'plik → artiklsiz.", "Общее множественное → без артикля."),
      P("Tartib son → the first.", "Порядковое числительное → the first."),
      P("Mavhum umumiy → Life is hard.", "Абстрактное общее → Life is hard."),
      P("Umumiy sanoqsiz → nature (artiklsiz).", "Общее неисчисляемое → nature (без артикля)."),
      P("the rich (guruh) + the advice (aniqlangan).", "the rich (группа) + the advice (конкретизировано)."),
      P("Umumiy → Most people ('the'siz 'of' yo'q).", "Общее → Most people (без the нет 'of')."),
      P("'the history of art': aniqlangan 'the history', umumiy 'art'.", "'the history of art': конкретное 'the history', общее 'art'."),
      P("'advice' sanoqsiz → artiklsiz, ko'pliksiz.", "'advice' неисчисляемое → без артикля и множественного числа."),
    ],
  },
};
