// Uzbek/Russian translations of reading & listening quiz explanations (A2–B2).
const P = (uz, ru) => ({ uz, ru });
export const QUIZ_TR = {
  A2: {
    r1: [
      P("Ular Manchesterdan poyezdga o'tirishdi.", "Они сели на поезд из Манчестера."),
      P("Avval ular Britaniya muzeyiga borishdi.", "Сначала они посетили Британский музей."),
      P("Muzey bepul edi.", "Музей был бесплатным."),
      P("Tushdan keyin ular qayiqda sayr qilishdi.", "После обеда они отправились на прогулку на лодке."),
      P("Ular charchagan, lekin baxtli edi.", "Они были уставшими, но счастливыми."),
    ],
    r2: [
      P("U Bristoldagi kitob do'konida ishlaydi.", "Она работает в книжном магазине в Бристоле."),
      P("Tajribasi yo'qligi uchun u hayajonlanardi.", "Она нервничала, потому что у неё не было опыта."),
      P("Janob Clarke mehribon va sabrli edi.", "Мистер Кларк был добрым и терпеливым."),
      P("U yarim stavkada, haftada uch kun ishlaydi.", "Она работает неполный день, три дня в неделю."),
      P("U universitetda adabiyot o'qimoqchi.", "Она хочет изучать литературу в университете."),
    ],
    r3: [
      P("U Braytondagi kichkina mehmonxonada.", "Он в небольшом отеле в Брайтоне."),
      P("U hali xarid qilishga bormagan.", "Он ещё не ходил по магазинам."),
      P("Suv ancha sovuq edi.", "Вода была довольно холодной."),
      P("Bugun ertalab biroz yomg'ir yog'di.", "Сегодня утром немного шёл дождь."),
      P("U shanba kuni uyda bo'ladi.", "Он будет дома в субботу."),
    ],
    r4: [
      P("Shaharlarda ish o'rinlari va mashg'ulotlar ko'proq.", "В городах больше работы и развлечений."),
      P("Shaharlar qimmatroq va gavjumroq.", "Города дороже и многолюднее."),
      P("Kichik shaharlarda odamlar ko'pincha samimiyroq.", "Люди в маленьких городах часто дружелюбнее."),
      P("U yerda ish o'rinlari kam va qiladigan ish oz.", "Там меньше работы и меньше занятий."),
      P("Endi muallif kichik shaharning osoyishtaligini afzal ko'radi.", "Теперь автор предпочитает спокойствие маленького города."),
    ],
    r5: [
      P("U ishdan uyga shoshilayotgan edi.", "Она спешила домой с работы."),
      P("Avtobusga shoshilib chiqayotganda telefon o'rindiqqa tushib qoldi.", "Телефон упал на сиденье, когда она спешила в автобус."),
      P("Uning suratlari va xabarlari telefonda edi.", "Её фотографии и сообщения были в телефоне."),
      P("U ekranda uning ma'lumotlarini ko'rib, email yubordi.", "Он написал ей письмо, увидев её данные на экране."),
      P("Harry telefonni qaytardi va endi ular yaxshi do'stlar.", "Гарри вернул телефон, и теперь они хорошие друзья."),
    ],
    l1: [
      P("Suhbat o'tkazuvchi uning ismi Lucy ekanini tasdiqlaydi.", "Интервьюер подтверждает, что её зовут Люси."),
      P("Uning ikki yillik tajribasi bor.", "У неё два года опыта."),
      P("U Lidsdagi do'konda ishlagan.", "Она работала в магазине в Лидсе."),
      P("Ish yarim stavkada, haftada to'rt kun.", "Работа на неполный день, четыре дня в неделю."),
      P("U kelasi dushanbadan boshlashi mumkin.", "Она может начать в следующий понедельник."),
    ],
    l2: [
      P("U ikki kechaga xona olmoqchi.", "Он хочет номер на две ночи."),
      P("Xona ikki katta yoshli kishi uchun.", "Номер для двух взрослых."),
      P("Ikki kishilik xona bir kechasi to'qson funt.", "Двухместный номер стоит девяносто фунтов за ночь."),
      P("Narxga nonushta kiritilgan.", "В цену включён завтрак."),
      P("Ular uni juma kuni kutishadi.", "Его ждут в пятницу."),
    ],
    l3: [
      P("Shanba kuni u Oksforddagi buvisinikiga boradi.", "В субботу она навещает бабушку в Оксфорде."),
      P("Buvisi Oksfordda yashaydi.", "Её бабушка живёт в Оксфорде."),
      P("Havo yaxshi bo'lsa, u velosipedda sayr qiladi.", "Она поедет кататься на велосипеде, если будет хорошая погода."),
      P("U dushanbadagi imtihoniga tayyorlanishi kerak.", "Ему нужно готовиться к экзамену в понедельник."),
      P("Uning imtihoni dushanba kuni.", "Его экзамен в понедельник."),
    ],
    l4: [
      P("Bu Londonga boradigan o'n o'ttizdagi poyezd.", "Это поезд в Лондон в десять тридцать."),
      P("Poyezd yomon ob-havo tufayli kechikmoqda.", "Поезд задерживается из-за плохой погоды."),
      P("Kechikish taxminan yigirma daqiqa.", "Задержка около двадцати минут."),
      P("Endi u to'rtinchi platformadan jo'naydi.", "Теперь он отправится с четвёртой платформы."),
      P("Ular Gatwickda boshqa poyezdga o'tishlari kerak.", "Им нужно сделать пересадку в Гатвике."),
    ],
  },
  B1: {
    r1: [
      P("U buxgalter bo'lib ishlagan edi.", "Он работал бухгалтером."),
      P("U o'zini zerikkan va holdan toygan his qilardi.", "Он чувствовал скуку и усталость."),
      P("U qo'l mehnatini yaxshi ko'rishini kashf qildi.", "Он обнаружил, что любит работать руками."),
      P("U avvalgidan kamroq pul topadi.", "Он зарабатывает меньше, чем раньше."),
      P("U ancha baxtliroq va buni ertaroq qilmaganidan afsuslanadi.", "Он гораздо счастливее и жалеет, что не сделал этого раньше."),
    ],
    r2: [
      P("U u yerga borgan va ob-havo hamda taomlarni yoqtirib qolgan edi.", "Она бывала там и полюбила погоду и еду."),
      P("Til tufayli oddiy ishlar ham stressli bo'lardi.", "Из-за языка простые дела становились стрессом."),
      P("U o'zini yolg'iz his qilar va oilasini sog'inardi.", "Она чувствовала себя одинокой и скучала по семье."),
      P("U mahalliy ispan tili kursida yangi kelganlar bilan tanishdi.", "На местных курсах испанского она познакомилась с новичками."),
      P("Bu u qilgan eng qiyin, lekin eng yaxshi ish edi.", "Это было самое трудное, но и самое лучшее её решение."),
    ],
    r3: [
      P("Matnda iroda emas, odat deyilgan.", "В тексте говорится о привычке, а не о силе воли."),
      P("Odat — takrorlanadigan, avtomatik harakat.", "Привычка — это повторяющееся автоматическое действие."),
      P("Avtomatik bo'lgach, kuch sarflash kerak emas.", "Когда действие автоматично, усилий уже не нужно."),
      P("Kichikdan boshlang, masalan, o'n daqiqadan.", "Начинайте с малого, например с десяти минут."),
      P("Yangi odatni mavjud odatga bog'lang.", "Привяжите новую привычку к уже существующей."),
    ],
    r4: [
      P("Bu kurtka haqidagi shikoyat xati.", "Это письмо-жалоба по поводу куртки."),
      P("U to'q ko'k emas, qora edi.", "Она была чёрной, а не тёмно-синей."),
      P("Bitta cho'ntagida teshik bor edi.", "В одном кармане была дырка."),
      P("Ular pulni to'liq qaytarishni so'rashadi.", "Они требуют полного возврата денег."),
      P("Kurtkaning fotosurati.", "Фотография куртки."),
    ],
    r5: [
      P("U ma'lumot to'pladi, javoblarni mashq qildi va kiyim tanladi.", "Она изучила компанию, отрепетировала ответы и выбрала одежду."),
      P("Uning poyezdi bekor qilingan edi.", "Её поезд отменили."),
      P("U tushunish bilan qabul qildi va o'z voqeasini aytib berdi.", "Он отнёсся с пониманием и рассказал свою историю."),
      P("Bir haftadan keyin u ishga qabul qilindi.", "Через неделю она получила работу."),
      P("Bu menejerga uning bosim ostida qanday harakat qilishini ko'rsatdi.", "Это показало менеджеру, как она справляется с давлением."),
    ],
    l1: [
      P("Riverside Booksdan janob Clarke qo'ng'iroq qilmoqda.", "Звонит мистер Кларк из Riverside Books."),
      P("U unga ish taklif qilmoqda.", "Он предлагает ей работу."),
      P("Maosh — yigirma to'rt ming funt.", "Зарплата — двадцать четыре тысячи фунтов."),
      P("U birinchi iyundan boshlashi kerak.", "Она должна начать первого июня."),
      P("U juma kunigacha javob berishi kerak.", "Она должна ответить до пятницы."),
    ],
    l2: [
      P("Ular Italiyaga sayohat qilmoqchi.", "Они хотят поехать в отпуск в Италию."),
      P("Har bir kishi uchun olti yuz funt.", "Шестьсот фунтов с человека."),
      P("Nonushta kiritilgan, boshqa ovqatlar esa yo'q.", "Завтрак включён, но не остальные приёмы пищи."),
      P("Taxminan ikki yarim soat.", "Около двух с половиной часов."),
      P("Yuz funt miqdorida oldindan to'lov.", "Задаток в сто фунтов."),
    ],
    l3: [
      P("U shahardagi oziq-ovqat bankida ko'ngilli bo'lib ishlaydi.", "Он волонтёрит в городском продовольственном банке."),
      P("Bir xayriya tashkiloti unga yordam bergan, shuning uchun u ham yordam qaytarmoqchi bo'lgan.", "Благотворительная организация помогла ему, и он захотел отплатить добром."),
      P("U oziq-ovqat yig'adi va oilalar uchun joylaydi.", "Он собирает продукты и упаковывает их для семей."),
      P("Haftada taxminan ikki kun.", "Примерно два дня в неделю."),
      P("Odamlar bilan tanishish va haqiqiy o'zgarish yaratish.", "Знакомиться с людьми и приносить реальную пользу."),
    ],
    l4: [
      P("U jamoat markaziga aylanadi.", "Она станет общественным центром."),
      P("U uch yildan beri yopiq.", "Оно закрыто уже три года."),
      P("Bepul kurslar, kafe va guruhlar uchun joy.", "Бесплатные занятия, кафе и помещение для групп."),
      P("Ko'p qismi hukumatdan kelgan.", "Большая часть поступила от правительства."),
      P("Ular pul maktablarga berilishi kerak edi, deb hisoblashadi.", "Они считают, что деньги следовало отдать школам."),
    ],
  },
  B2: {
    r1: [
      P("U ish va shaxsiy hayot muvozanatini yaxshilaydi.", "Она даёт лучший баланс работы и личной жизни."),
      P("Masofadagi xodimlarni nazorat qilish qiyinroq va ular jamoadan uzilib qoladi.", "Удалённых сотрудников сложнее контролировать, и они менее вовлечены."),
      P("Ular tajribali hamkasblardan norasmiy o'rganish imkonini boy berishi mumkin.", "Они могут упустить неформальное обучение у опытных коллег."),
      P("Haftaning bir qismi uyda, bir qismi ofisda.", "Часть недели дома, часть — в офисе."),
      P("U tobora ikkala dunyoning eng yaxshi tomoni sifatida qaralmoqda.", "Её всё чаще считают лучшим из обоих миров."),
    ],
    r2: [
      P("U filmlar tavsiya qiladi, emaillarni filtrlaydi va tasvirlarni o'qishga yordam beradi.", "Он рекомендует фильмы, фильтрует письма и помогает читать снимки."),
      P("U ko'plab tasvirlarni tez ko'rib chiqib, qonuniyatlarni aniqlay oladi.", "Он быстро анализирует множество снимков и находит закономерности."),
      P("O'zi boshqariladigan mashina avariyasi uchun kim javobgarligi.", "Ответственность за аварию беспилотного автомобиля."),
      P("Ular yangi ish o'rinlari yaratiladi, deb ta'kidlashadi.", "Они утверждают, что появятся новые рабочие места."),
      P("AI endi doimiy hodisa; jamiyatlar undan qanday foydalanishni hal qilishi kerak.", "ИИ уже никуда не денется; общества должны решить, как его использовать."),
    ],
    r3: [
      P("Bu dangasalikdan ko'ra ko'proq hissiyot bilan bog'liq.", "Это больше связано с эмоциями, чем с ленью."),
      P("Chalg'ish yomon his-tuyg'ulardan bir zumda yengillik beradi.", "Отвлечение даёт мгновенное облегчение от неприятных чувств."),
      P("Yengillik uzoq davom etmaydi, vazifa esa yanada stressli bo'lib boradi.", "Облегчение недолговечно, а задача становится всё более стрессовой."),
      P("Katta vazifani kichik qadamlarga bo'ling.", "Разбивайте большую задачу на маленькие шаги."),
      P("O'zini tanqid qilishni to'xtatgan talabalar kamroq paysalga solgan.", "Студенты, переставшие себя критиковать, меньше прокрастинировали."),
    ],
    r4: [
      P("Kutubxonani baholash va yaxshilashlar tavsiya qilish.", "Оценить библиотеку и рекомендовать улучшения."),
      P("200 foydalanuvchi o'rtasida so'rov va xodimlar bilan suhbatlar.", "Опрос 200 пользователей и интервью с сотрудниками."),
      P("Kitoblarning keng tanlovi.", "Широкий выбор книг."),
      P("Qo'pol xodimlar haqida aytilmagan.", "Грубость персонала не упоминалась."),
      P("Tinch o'quv zonasi yaratish talabalarni jalb qilardi.", "Создание тихой учебной зоны привлекло бы студентов."),
    ],
    r5: [
      P("Sayohat hech qachon bunchalik arzon bo'lmagan.", "Путешествия никогда не были такими доступными."),
      P("Ekologik xarajat (karbonat angidrid chiqindilari).", "Экологическая цена (выбросы углерода)."),
      P("Haddan tashqari gavjumlik mahalliy aholini siqib chiqarmoqda.", "Переполненность вытесняет местных жителей."),
      P("To'xtash emas, balki o'ylabroq sayohat qilish kerak.", "Нужно путешествовать осознаннее, а не прекращать."),
      P("Sayyohlar va hukumatlar birgalikda harakat qilishi kerak.", "Туристы и правительства должны действовать сообща."),
    ],
    l1: [
      P("U qaror qabul qilish psixologiyasi haqida.", "Она посвящена психологии принятия решений."),
      P("Ko'pchilik qarorlarni hissiyot va aqliy yo'l-yo'riqlar boshqaradi.", "Большинство решений определяются эмоциями и ментальными сокращениями."),
      P("Odatda foydali, lekin bashorat qilsa bo'ladigan xatolarga olib kelishi mumkin.", "Обычно полезны, но могут приводить к предсказуемым ошибкам."),
      P("Yo'qotishdan qo'rqish xuddi shunday yutuqni qadrlashdan kuchliroq.", "Страх потери сильнее, чем ценность равного выигрыша."),
      P("Kelasi haftadagi seminardan oldin to'rtinchi bobni o'qish.", "Прочитать четвёртую главу до семинара на следующей неделе."),
    ],
    l2: [
      P("Bu marketing sohasidagi lavozim.", "Это должность в маркетинге."),
      P("U ularning ijodiy kampaniyalariga qoyil qoladi va bu o'ziga mos deb hisoblagan.", "Она восхищается их креативными кампаниями и почувствовала, что это ей подходит."),
      P("Yirik mijozni yo'qotib, keyin uchta kichikroq mijozni qaytarib olish.", "Потеря крупного клиента и возвращение трёх клиентов поменьше."),
      P("Shu kompaniyada o'z jamoasini boshqarish.", "Руководить собственной командой в этой компании."),
      P("Hafta oxirigacha.", "До конца недели."),
    ],
    l3: [
      P("Ijtimoiy tarmoqlar foydadan ko'ra ko'proq zarar keltiradimi degan savol.", "Вопрос о том, приносят ли соцсети больше вреда, чем пользы."),
      P("U oilalarni bog'laydi va odamlarga ovoz beradi.", "Они соединяют семьи и дают людям голос."),
      P("Ko'p foydalanish o'smirlarda xavotir bilan bog'liq.", "Активное использование связано с тревожностью у подростков."),
      P("Ular real hayotni internetdagi mukammal tasvirlar bilan solishtirishadi.", "Они сравнивают реальную жизнь с идеальными картинками в сети."),
      P("Muammo undan qanday foydalanishimizda; ta'lim yordam berishi mumkin.", "Проблема в том, как мы им пользуемся; образование могло бы помочь."),
    ],
    l4: [
      P("Global harorat kutilganidan tezroq ko'tarilmoqda.", "Глобальные температуры растут быстрее, чем ожидалось."),
      P("Ular bir necha o'n yil ichida jiddiy suv toshqiniga duch kelishi mumkin.", "Им может грозить серьёзное затопление в ближайшие десятилетия."),
      P("Qayta tiklanadigan energiya narxi keskin tushdi.", "Стоимость возобновляемой энергии резко упала."),
      P("Texnologiya bor; siyosiy iroda yetishmayapti.", "Технологии есть; не хватает политической воли."),
      P("Ular va'dalar yana buziladi, deb qo'rqishadi.", "Они опасаются, что обещания снова будут нарушены."),
    ],
  },
};
